### ISSUE TITLE
Port remaining docs to JSDoc format

### ISSUE THREAD

**Issue by skddc** [remotestorage/remotestorage.js#1006]
I think we're done with the public API, but there are still NaturalDoc comments left for private API, and we should also tag any methods and properties not appearing in the new HTML docs as `@private` or `@protected`.

**Comment by galfert** [comment]
See [my comment](https://github.com/remotestorage/remotestorage.js/pull/997#commitcomment-24783253) about the use of `@private`.

I think we need to distinguish between internal documentaton for library implementors and public documentation for end-users here.

IMO the `@private` label should indicate that the method/property is private to that particular class only, so library implementors know not to use them from anywhere else.

For the user documentation, I think it's good enough to only list those methods that are for public consumption.

**Comment by skddc** [comment]
See my response. There's `@protected` for that.

**Comment by galfert** [comment]
ok

**Comment by skddc** [comment]
🎉
