### ISSUE TITLE
Test RC1 in all environments

### ISSUE THREAD

**Issue by skddc** [remotestorage/remotestorage.js#1032]
I think we haven't made sure that node.js works as intended, but have most other envs covered. Confirming Cordova again would also make sense. Just so we don't release a broken final.

**Comment by gregkare** [comment]
I started testing 1.0.0-rc1 on node. Here's the first issue with it:

```
$ node
> > var RemoteStorage = require('remotestoragejs');
... ReferenceError: XMLHttpRequest is not defined
...     at Object.<anonymous> (./node_modules/remotestoragejs/release/remotestorage.js:28:4332)
...     at t (./node_modules/remotestoragejs/release/remotestorage.js:2:352)
...     at Object.e.exports (./node_modules/remotestoragejs/release/remotestorage.js:28:53)
...     at t (./node_modules/remotestoragejs/release/remotestorage.js:2:352)
...     at Object.e.defaultValue (./node_modules/remotestoragejs/release/remotestorage.js:3:16231)
...     at t (./node_modules/remotestoragejs/release/remotestorage.js:2:352)
...     at Object.n (.node_modules/remotestoragejs/release/remotestorage.js:4:8757)
...     at t (./node_modules/remotestoragejs/release/remotestorage.js:2:352)
...     at Object.<anonymous> (./node_modules/remotestoragejs/release/remotestorage.js:2:472)
...     at t (./node_modules/remotestoragejs/release/remotestorage.js:2:352)
```

Including a dependency on a XMLHttpRequest library (such as xmlhttprequest) and instantiating a `XMLHttpRequest` variable before requiring `remotestorage` fixes it.

We used to require xhr2 as the XMLHttpRequest variable (c5d78f7d) and still have a dependency on it in package.json, but we're not using it in the code at the moment.

**Comment by skddc** [comment]
Please create new, seperate issues that we can work on for things that don't work currently. Thanks!
