### ISSUE TITLE
Error when uploading binary files to Dropbox

### ISSUE THREAD

**Issue by galfert** [remotestorage/remotestorage.js#1048]
Looks like the client is using a wrong content-type when uploading. The error response from Dropbox is:

> Error in call to API function "files/upload": Bad HTTP "Content-Type" header: "application/json; charset=UTF-8".  Expecting one of "application/octet-stream", "text/plain; charset=dropbox-cors-hack".

**Comment by skddc** [comment]
Then this is not an error with uploading binary files, but setting a content type in general?
