### ISSUE TITLE
Bower install failed

### ISSUE THREAD

**Issue by yassinphilip** [remotestorage/remotestorage.js#1112]
Hi ; [The manual states](https://remotestoragejs.readthedocs.io/en/latest/getting-started/how-to-add.html#adding-rs-js-to-an-app) that `remotestoragejs` is installable via bower, but there seem to be a problem with that :

```
./node_modules/bower/bin/bower install -S remotestoragejs
bower                        ENOTFOUND Package remotestoragejs not found

```

**Comment by skddc** [comment]
Oops. According to https://bower.io/search/ that might be just `rs` instead of `remotestoragejs`. Could you try that?

**Comment by yassinphilip** [comment]
Oooh :)


```
# ./node_modules/bower/bin/bower install -S rs             
bower rs#*                  not-cached https://github.com/remotestorage/remotestorage.js.git#*
bower rs#*                     resolve https://github.com/remotestorage/remotestorage.js.git#*
bower rs#*                    download https://github.com/remotestorage/remotestorage.js/archive/v1.0.2.tar.gz
bower rs#*                     extract archive.tar.gz
bower rs#*                    resolved https://github.com/remotestorage/remotestorage.js.git#1.0.2
bower remotestorage#^1.0.2     install remotestorage#1.0.2

remotestorage#1.0.2 bower_components/remotestorage

```

I guess someone should update the manual then :package: 
Thanks a lot, @skddc

**Comment by skddc** [comment]
(Btw, the manual has an "edit on Github" link in the upper right corner, btw. In case you want to get your first contribution in. 😉)

**Comment by yassinphilip** [comment]
> In case you want to get your first contribution in.

/bin/done :)

What about the widget then? Is there a bower install path?

**Comment by skddc** [comment]
> What about the widget then? Is there a bower install path?

Good point. I think nobody registered a bower package for that yet.
