### ISSUE TITLE
Google Drive and Dropbox images getFile corrupted

### ISSUE THREAD

**Issue by jojobyte** [remotestorage/remotestorage.js#1116]
Been trying to load images added to Drive or Dropbox via `storeFile`, however `getFile` is loading corrupt data.

```js
remoteStorage.scope('/images/')
.getFile('example.png').then(file => {
  // Neither of these work

  // try to create object url
  var blob = new Blob([file.data], { type: file.contentType });
  let bleh = URL.createObjectURL(blob);
  this.rsData.push(bleh);
  URL.revokeObjectURL(bleh);

  // try to create Data URL
  var reader = new FileReader();
  reader.onloadend = (e) => {
    this.rsData.push(e.target.result);
  };
  reader.readAsDataURL(blob);
});
```

Tried a ton of different combinations, the images appear correctly when viewing in google drive and dropbox UI, so I think its a problem with the getFile function.

```js
// this is what the image should start with as a data url
data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAArwAAAK8CAMAA...

// this is what keeps coming thru, the corrupt versions all seem to start with "77+"
data:image/png;base64,77+9UE5HDQoaCgAAAA1JSERSAAAC77+9AAAC77...
data:image/jpeg;base64,77+977+977+977+9ABBKRklGAAEBAQEsASwAAO...
```

Any help would be much appreciated. Let me know if you have any follow up questions. Would love to get this figured out.

using `"remotestoragejs": "^1.0.2"`

**Comment by skddc** [comment]
This looks like a bug indeed. Someone knows where to start debugging here?

**Comment by galfert** [comment]
> Someone knows where to start debugging for this one?

Not really, but I'll try to find some time to have a look.

**Comment by iLiviu** [comment]
This happens because both Dropbox and Googledrive backends first read the response as text and then try to convert it back to raw value, however not all bytes can be encoded as text, and are lost during the conversion to text and back. I am working on a fix.
