### ISSUE TITLE
storageApi is not set after connecting to 5apps.com

### ISSUE THREAD

**Issue by karlb** [remotestorage/remotestorage.js#1120]
While investigating a case of missing 'conflict' events, I found that in my case no If-Match headers got used. After adding some additional debug output, I noticed that no storageApi is set and thus supportsRevs is false when [calling WireClient.put](https://github.com/remotestorage/remotestorage.js/blob/master/src/wireclient.js#L460).

This happens for me both with Firefox and Chrome. Here are the request headers when using [favorite drinks](https://myfavoritedrinks.remotestorage.io):

```
PUT /karlb/myfavoritedrinks/test HTTP/1.1
Host: storage.5apps.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:59.0) Gecko/20100101 Firefox/59.0
Accept: */*
Accept-Language: en-US,en;q=0.7,de;q=0.3
Accept-Encoding: gzip, deflate, br
Referer: https://myfavoritedrinks.remotestorage.io/
Content-Type: application/json; charset=UTF-8
Authorization: Bearer [REMOVED]
Content-Length: 88
Origin: https://myfavoritedrinks.remotestorage.io
Connection: keep-alive
```

**Comment by galfert** [comment]
Could you please run the following in your console?

`JSON.parse(localStorage.getItem('remotestorage:discover')).cache['karlb@5apps.com'].storageType;`



Does that return the value `"draft-dejong-remotestorage-06"`?

**Comment by karlb** [comment]
Yes, it does.

**Comment by skddc** [comment]
Confirmed: I also don't see `If-Match` headers with the latest version!

**Comment by skddc** [comment]
I have a fix for this ready now: https://github.com/remotestorage/remotestorage.js/commit/9f8e06d00f58

Looking at tests, before opening a PR.

**Comment by karlb** [comment]
I can still reproduce the problem on https://myfavoritedrinks.remotestorage.io/ , which seems to use release 1.0.3. Do I have to do anything special for the fix to take effect?

**Comment by skddc** [comment]
Did you reconnect your account?

Edit: I do see the If-Match header on PUTs, but it can only be attached when you update an existing, cached document, of course.
Edit 2: most people don't reconnect their account often or at all, so I'm wondering how we could handle that.

**Comment by karlb** [comment]
For some reason reconnecting didn't help, but emptying localStorage did.

**Comment by galfert** [comment]
Just a sidenote: Myfavoritedrinks doesn't update any existing entries, you can only create new drinks and delete existing ones. But when creating a new entry, it should send a `If-None-Match` header with value `"*"`.

**Comment by skddc** [comment]
@galfert Oh but it does. Try adding the same drink a second time. ;)
