### ISSUE TITLE
remostorage VS IPFS

### ISSUE THREAD

**Issue by ydennisy** [remotestorage/remotestorage.js#1125]
Hello,
I am weighing up various options/protocols for a user owned storage system.
My question is; it seems quite limiting to need users to "own" a remoteStorage server, what is the normal flow for apps here, do they host the server? If yes - what is the difference to a traditional app?
Thanks in advance.
Dennis

**Comment by silverbucket** [comment]
Hi @ydennisy - sorry for the late response. With remoteStorage you have the option to run your own service, but it's not required. There are providers of remoteStorage out there, so you don't have to worry about setting it up yourself. The idea is that when you use a remoteStorage enabled app, you point it to your storage service during initialization. That's the main difference between "traditional" apps (though I suppose apps are changing too often for there to be a traditional type of app), and unhosted or serverless apps. Does this answer your question?
