### ISSUE TITLE
No longer works in web worker since version 1.0.3

### ISSUE THREAD

**Issue by icidasset** [remotestorage/remotestorage.js#1126]
Hey folks 👋 

I was using version `1.0.2` in my project and decided to upgrade to `1.0.3`.
But now I'm getting the following error:

```js
Uncaught ReferenceError: window is not defined
```

The issue only pops up in web workers.

I'm using remoteStorage through browserify and I'm requiring it as follows:

```js
self.RemoteStorage = require("remotestoragejs/release/remotestorage");
```

Any thoughts?
Thanks!

**Comment by skddc** [comment]
Thanks for the report. Can you confirm that 1.0.2 does not have the same issue in a Web Worker?

**Comment by icidasset** [comment]
@skddc Yeah, works fine with 1.0.2.

**Comment by galfert** [comment]
I think the issue might be in the build generated by Webpack.

In version 1.0.3 the build contains this:

```js
[...] exports.RemoteStorage=t():e.RemoteStorage=t()}(window,function(){ [...]
```

while in version 1.0.2 it looked like this:

```js
[...] exports.RemoteStorage=t():e.RemoteStorage=t()}(this,function(){ [...]
```

using `this` instead of `window`.

**Comment by skddc** [comment]
Ah, we did update Webpack to a new major at some point. Thanks for the confirmation.
