### ISSUE TITLE
Fetch API breaks Dropbox and GoogleDrive support

### ISSUE THREAD

**Issue by iLiviu** [remotestorage/remotestorage.js#1151]
The problem is that if no `responseType` property is present in `options ` parameter to `WireClient._fetchRequest`, the function defaults to `document` and throws an error. If `responseType `is `undefined`, the function should treat the response as `text`. Also, if the response is treated as `text` , the `syntheticXhr.responseText` property should be set to `processedBody` in order to not break XHR compatibility.

**Comment by skddc** [comment]
Merged and released. Thanks for reporting and fixing, @iLiviu!
