### ISSUE TITLE
Dropbox backend does not pick up remote changes for subfolders

### ISSUE THREAD

**Issue by iLiviu** [remotestorage/remotestorage.js#1154]
The fix #1129 for issue #1128 only fixes picking up remote changes for root folder. If the root folder has subfolders, and the content of a subfolder changes remotely, the change is not picked up by the backend. There was some strange code i couldn't understand why it was there but when i investigated the history of dropbox.js i discovered that initially it was using Dropbox V1 API. The problems appeared once the code was switched to V2 API which no longer offers revision ids for folders. 

As a solution, i propose hashing the contents of the folder locally in the client and use that as a revision id. I can work on this.

**Comment by skddc** [comment]
> The problems appeared once the code was switched to V2 API which no longer offers revision ids for folders.

Ouch, that's a problem indeed. Good catch!

> As a solution, i propose hashing the contents of the folder locally in the client and use that as a revision id. I can work on this.

Sounds like a good idea. Not sure what Dropbox do themselves in order to learn about subfolder changes though. Maybe their own code could give us some hints.

**Comment by iLiviu** [comment]
> Sounds like a good idea. Not sure what Dropbox do themselves in order to learn about subfolder changes though. Maybe their own code could give us some hints.

Our sync API requires a revision for folders in order to detect changes (or  no revision at all and the updated content of each folder is requested from Dropbox on every sync). So we need to generate such a unique id. 

Dropbox API suggests that after the initial (recursive) list of the root folder, one should use the `cursor` provided, so that only changes will be listed on next call. The optimum way would be to store the cursor and the entire folder tree in LocalStorage.  A compromise (which i prefer so we don't fill up LocalStorage if our folder tree is huge) would be to list the entire tree on initialization (as it is now), and store the folder tree and cursor in memory for use in the current session only. From the stored folder tree, we can generate a revision id for folders by combining the revision ids of all files in folder and hashing them. For the parent folder revision id, we will also include the subfolder's generated hash when concatenating revision ids for it's hash.
