### ISSUE TITLE
Not syncing the data with server when same user added the data from multiple browser

### ISSUE THREAD

**Issue by ramvasanth** [remotestorage/remotestorage.js#1157]
I have created a user(A) and i logged into two browsers with same user(A) and i created a note from browser 1 that contains  data **payload1** and save it to server and then i pull this data into browser 2 and save it as **payload2**  to server and then i sync the browser 1 but it still shows **payload1**  ?

please help  whether this scenario is supported by remote-storage ?

**Comment by skddc** [comment]
Yes, this is definitely supported. It could be either a bug with the app (more likely), or a bug in this library (less likely). You can try a different app to verify that it works in general. For example you can add bookmarks in two different browsers using [Webmarks](https://webmarks.5apps.com) and the changes in one browser should show up in the other browser after about 10 seconds latest (default sync interval is 10s).

However, there's also [an open bug](https://github.com/remotestorage/remotestorage.js/issues/1137) for syncing in the *same* browser, but in different tabs/windows. But in any case, a reload or newly opening the app would always sync your data.

**Comment by ramvasanth** [comment]
Hi @skddc i tried https://webmarks.5apps.com/ 

Every time when i change the attributes such as URL or Title it creates a duplicate webmark, i could not test properly for my test cases

**Comment by skddc** [comment]
Which note taking app are you referring to? This is definitely not an issue in the current release version of this library. I double-checked that it works in Webmarks.

**Comment by skddc** [comment]
@ramvasanth Just FYI: I made a lot of changes to Webmarks over the last 1.5 weeks.

I'll close this issue, as there's no bug in remoteStorage.js that I can identity from it. I think it would still be interesting to know which app the bug appears in, and to report that bug to the app developer(s).
