### ISSUE TITLE
Wrong comparison?

### ISSUE THREAD

**Issue by vladimiry** [remotestorage/remotestorage.js#1164]
https://github.com/remotestorage/remotestorage.js/blob/536c534f93fff347356828f92d56b0fb7d458b41/src/sync.js#L635

A string value `typeof(node.common.body)` is being compared to undefined, so the condition will always evaluate to true. I guess `"undefined"` string was intended to be used at the right side.

**Comment by galfert** [comment]
Good catch. Thanks for pointing it out. I fixed it in 1f292bb.
