### ISSUE TITLE
Clear auth & backend data at the end of the browser session

### ISSUE THREAD

**Issue by wvoelcker** [remotestorage/remotestorage.js#1166]
Hello, I have been trying out the library recently, and have to say: great work.

One config option I would find useful would be to clear the user's auth session after they close the browser, so that it is safer to use remotestorage.js on shared computers.

Sorry if I have missed a way to do this; is there any available, and if not, do you have any comments on the idea of adding one?

**Comment by skddc** [comment]
There's currently no way of doing this on the library side, as it uses the much faster `IndexedDB` as a local database, and what you suggest would mean having to use the much slower `SessionStorage` for that option. The latter is not designed to handle a lot of data.

Also, the idea of the library is that once you connected your storage, you only ever sync added or changed data across machines, and you hardly ever disconnect your storage. Shared computers (or browsers) should generally handle this by giving users their own account, or having a guest account that automatically deletes locally stored data after a session.

That being said, there's an easy solution that already exists in all browsers today, and it's there for this exact reason: use a private window/tab on shared computers, and it will delete your synced RS data as soon as you close the private window/tab. In fact, the library has been tested specifically to support private mode in all browsers, and we fixed a variety of bugs in this area in the past.

Hope this helps.

**Comment by wvoelcker** [comment]
Thank you for replying!  That's useful and interesting.

In don't trust my users to use private tabs, so I'm hacking into my fork the option of using sessionStorage rather than localStorage when the cache is turned off (which it is, in my case).

It's rather quick and dirty, and I haven't written tests yet, but if you're interested, the code is here: https://github.com/remotestorage/remotestorage.js/compare/master...wvoelcker:master
