### ISSUE TITLE
Get the file directly from server

### ISSUE THREAD

**Issue by ramvasanth** [remotestorage/remotestorage.js#1167]
We have this following scenario:
User can have multiple profiles and one active profile. Every time when the app is launched without local data in the browser , it has to wait for all the profiles to be synced before we can get the default profile. this behavior is causing some issues to our app. 

what we really want is: 
when the app is launched , it has to get the default profile data from remote storage server without waiting for full sync because user could have n number of profiles.

how do we get the file directly from server without waiting for full sync ?

Thanks.

**Comment by galfert** [comment]
I think you could use the [`getObject`](https://remotestoragejs.readthedocs.io/en/latest/js-api/base-client.html#getObject) method with a `maxAge` value of `0`. That way it won't use the local cache but directly requests the file from the remote server.

**Comment by skddc** [comment]
You can define exactly when and how a certain URL path should be cached (and it will include all subdirectories of that path by default). So I think the most elegant way to solve this, is to only activate caching for the non-default profiles, after the default profile has been synced/retrieved.

Consider this (totally untested) example:

```js
remoteStorage.caching.enable('/my-category/profiles/default/');
const client = remoteStorage.scope('/my-category/');

remoteStorage.on('connected', async function () {
  const defaultProfileData = await client.getAll('profiles/default/');
  remoteStorage.caching.enable('/my-category/profiles/'); // Enable caching/sync for all other profiles
  // ...
});
```

See https://remotestoragejs.readthedocs.io/en/latest/js-api/caching.html for detailed documentation.

**Comment by ramvasanth** [comment]
Thanks guys
