### ISSUE TITLE
Google Drive Folders with "special characters" get duplicated.

### ISSUE THREAD

**Issue by kevincox** [remotestorage/remotestorage.js#1176]
Possibly related to: https://github.com/remotestorage/remotestorage.js/issues/682

Example code:
```html
<body>
<script src="https://unpkg.com/remotestoragejs@1.2.3/release/remotestorage.js"></script>
<script src="https://unpkg.com/remotestorage-widget@1.5.1/build/widget.js"></script>
<script>
const remoteStorage = new RemoteStorage();
remoteStorage.setApiKeys({
	googledrive: "$apikey",
});

setTimeout(() => new Widget(remoteStorage).attach(), 1000);

remoteStorage.access.claim("ca.kevincox.example", "rw");

remoteStorage.on("connected", () => {
	let scope = remoteStorage.scope("/ca.kevincox.example/");
	// Works
	// scope.storeFile("text/plain", "file", "foobar");
	// Loops forever
	scope.storeFile("text/plain", "some folder/file.json", "");
});
</script>
```

The file `file.json` never gets wrtten and there are constant network requests creating new folders called "some folder".

**Comment by kevincox** [comment]
A workaround is encoding the problematic segments with the following transform: `btoa(title).replace(/=+$/, "")`. Note that leaving the `=` at the end causes the same problem.

But even this is not flawless. While it will eventually write *a* file there may still be duplicated path segments leading up to it.

![image](https://user-images.githubusercontent.com/494012/78580229-1a9c3780-7800-11ea-9081-11c5b77e5af5.png)

**Comment by kevincox** [comment]
Thanks for the fix, could a release be made which includes this?

**Comment by skddc** [comment]
I think we could take a look at #1179 before the next release, so they're both solved.
