### ISSUE TITLE
Synconconnect may block startup data request.

### ISSUE THREAD

**Issue by androidfans** [remotestorage/remotestorage.js#1183]
when app first launch , I want to load data from local db as soon as possible. but due to the synconconnect. my request will be block util sync finish
please add a timeout option for start up sync

**Comment by skddc** [comment]
Welcome @androidfans!

I assume what you're trying to explain is that when using `client.getAll()` or `getObject()`, it will check the remote for changes first?

If so, you can set the `maxAge` argument to `false`. (In that case, make sure you implement [change event handlers](https://remotestoragejs.readthedocs.io/en/latest/js-api/base-client.html#change-events), so that your app is still notified of incoming new and updated documents from the remote storage.)

You can find the relevant documentation here:

https://remotestoragejs.readthedocs.io/en/latest/js-api/base-client.html#caching-logic-for-read-operations

Hope this helps. Let me know if this was actually the question, or if I misread it.

**Comment by androidfans** [comment]
```javascript

                        const remoteStorage  = new RemoteStorage({logging: true, modules: [], cache : true});
                        remoteStorage.setBackend('googledrive');
                        remoteStorage.setApiKeys({
                            googledrive: "dummykey"
                        })
                        remoteStorage.googledrive.configure({
                            token: authResult   // authresult is managed by my self
                        })
                        remoteStorage.access.claim('mydata', 'rw');


                    //vuex.dispath("fetch_firstscreen_data")
                   // then i called privateClient.getAll('') in dispatched method "fetch_firstscreen_data".
                   // I have noticed almost every time .  it will do a sync first . then my privateClient.getAll('')  method got a callback sequently.   the sync takes a long time
```

**Comment by androidfans** [comment]
I am developing a chrome extension. so the chrome_token is requested in a different way.  so I manage the token manuly

**Comment by skddc** [comment]
Yes, so the `maxAge` argument is what you want to learn about. Please follow the link I have included in my last comment, where it is described.

**Comment by androidfans** [comment]
@skddc  thanks . I am going to take a look

**Comment by skddc** [comment]
Your call would look like this:

```js
privateClient.getAll('', false);
```

**Comment by skddc** [comment]
I added an issue to improve the getting-started docs in this regard, because it is a pretty essential part of how to use the library.

**Comment by androidfans** [comment]
Thx @skddc .  And it will be better if library can autodetect `chrome.extension` varible then use `chrome.identity.getAuthToken` to get access_token automatically

**Comment by skddc** [comment]
You mean for connecting a Google Drive account? I didn't know Chrome even does that.

**Comment by androidfans** [comment]
@skddc yes. chrome provide this shortcut for extension. you only need to add appKey in extension manifest
https://developer.chrome.com/apps/identity#method-getAuthToken

**Comment by skddc** [comment]
I don't think this will give you access to a user's Drive/storage, but only to their Chrome profile (and possibly Chrome-specific storage for extensions and such).

**Comment by skddc** [comment]
... maybe this could be one of the connect options when using the library in Chrome, but then we'd also need a new storage adapter in the library to deal with this particular API.

**Comment by androidfans** [comment]
Hi, @skddc . I have just found another amazing api can be used in chrome app/extension.
https://developer.chrome.com/apps/syncFileSystem. It handle the sync logic well.
It provides **app-specific syncable storage** for offline and caching usage so that the same data can be available across different clients which will not conflict with doc created by user

**Comment by skddc** [comment]
Cool. But that API doesn't do anything that remoteStorage.js doesn't already do. Except it only works in Chrome, and this library works in all browsers...
