### ISSUE TITLE
Directories deleted on Google Drive side still found in remoteStorage

### ISSUE THREAD

**Issue by sorentycho** [remotestorage/remotestorage.js#1194]
Steps to reproduce:
1. Connect Google Drive to a remoteStorage.js app
2. Create a directory via remoteStorage.js
3. Add some files to the directory
4. "Delete" (move to trash) the directory
5. remoteStorage.js still sees the file as if it's at its old location

**Comment by galfert** [comment]
The [Google Drive API documentation](https://developers.google.com/drive/api/v2/reference/files#resource) lists a boolean property `labels.trashed`.

That one should be used to filter out any files or directories from the listings.
