### ISSUE TITLE
Dropbox: support for "App folder" access

### ISSUE THREAD

**Issue by pataquets** [remotestorage/remotestorage.js#1208]
Current implementation requires granting access to all files in your Dropbox.

If "app access" is used, applications are restricted to a single Dropbox directory, without any access to files outside it.

Granting so much access might be a bit scary sometimes and app access gives users peace of mind.

https://www.dropbox.com/developers/reference/developer-guide

**Comment by johannesjo** [comment]
That should be already the case:

![Screenshot from 2020-11-09 19-07-09](https://user-images.githubusercontent.com/1456265/98579400-e79eb280-22be-11eb-904c-6e5e00b6b650.png)

Maybe you need to refresh your token to see it?

**Comment by johannesjo** [comment]
Sorry. Wrong project...

**Comment by pataquets** [comment]
Oops! You're right. I'm afraid I'm barking at the wrong tree.
I'm experiencing this while using the Webmarks app:
https://webmarks.5apps.com

Thanks and sorry for the inconvenience.
