### ISSUE TITLE
DynamoDB storage

### ISSUE THREAD

**Issue by pataquets** [remotestorage/remotestorage.js#1209]
Amazon's k/v store. It would also make for a good fully serverless deployment, I guess.
They provide a free usage tier of 25Gb.

**Comment by raucao** [comment]
This library is only for client integration, not servers.

However, the [spec](https://datatracker.ietf.org/doc/draft-dejong-remotestorage/) is actually pretty simple, if you want to implement a compliant server (or server functions) based on AWS hosted products. Or you could e.g. add it as a storage adapter to [armadietto](https://github.com/remotestorage/armadietto/).
