### ISSUE TITLE
Don't run `npm install` on every local doc build

### ISSUE THREAD

**Issue by raucao** [remotestorage/remotestorage.js#1229]
It's even run when rebuilding the docs automatically with `autobuild`. It's part of the Sphinx/Python config file, and is needed to install our deps on RTD:

https://github.com/remotestorage/remotestorage.js/blob/ae30441bf1cd2c348592cd1cb326f5847bcbdbfb/doc/conf.py#L208

**Comment by raucao** [comment]
@pjbollinger Maybe you have an idea how we could run this only on RTD?

**Comment by pjbollinger** [comment]
I do, let me try to clean up that area of code a bit using Python's `pathlib` and add a conditional so if the script already has access to a locally installed`typedoc` via the repository, it will skip `npm install`.
