### ISSUE TITLE
Error connecting to Google Drive

### ISSUE THREAD

**Issue by yPhil-gh** [remotestorage/remotestorage.js#1235]
I'm trying to enable Google Drive using the [same code that I use - and works perfectly - for 5Apps](https://framagit.org/yphil/petrolette/-/blob/server/public/js/PTL.sync.js#L30), so I didn't have great hopes about it magically working on GDrive :) 

So what happens is the Auth page comes up, asking for permissions (the app is still on probation so you have to click past additional warnings) and then after clicking "allow" you're [redirected to the app](https://petrolette.space/), but the console says `Cannot read property 'queueGetRequest' of undefined` :(

The Widget has the Google Drive logo in place of the usual one though..?

So I was wondering, is there an implementation of Google Drive sync using the widget that I could look at?

**Comment by raucao** [comment]
[Webmarks](https://webmarks.5apps.com) ([source](https://github.com/raucao/webmarks)) should work AFAIK.

Could you let us know which version of the library this fails with?

**Comment by yPhil-gh** [comment]
> Webmarks (source) should work AFAIK.

Great, just what I needed, thanks.

> Could you let us know which version of the library this fails with?

From bower:
├── remotestorage 1.1.0 (latest is 2.0.0-alpha.7)
├── rs-widget 1.3.0 (latest is 1.5.2)

**Comment by raucao** [comment]
OK, that's good to know. Definitely also try with the current stable version, `v1.2.3`!

**Comment by yPhil-gh** [comment]
> Definitely also try with the current stable version, v1.2.3

Gosh, looks like it works. I don't have time to test thoroughly now (it's 00:30 AM here on the west coast of Africa) but now the widget definitely says "Connected" (I only reloaded the page) and the console too :)

**Comment by yPhil-gh** [comment]
Working now, using version v1.2.3.

**Comment by raucao** [comment]
That's great, but we need to keep the bug open for 2.0...
