### ISSUE TITLE
remoteStorage error event not returning expected response

### ISSUE THREAD

**Issue by murphypetercl** [remotestorage/remotestorage.js#1240]
Hi guys,
I'm trying to handle auth expiry in an app I'm playing with (i.e. when the widget displays the "App authorization expired or revoked, Renew" message). 

I am capturing the error as follows:

remoteStorage.on('error', (err) => {
    console.log('Remote storage - error')
    console.log(err)
  })

Per the documentation https://remotestoragejs.readthedocs.io/en/v1.2.3/js-api/remotestorage.html I expected to see something like: 

// {
//   name: "Unauthorized",
//   message: "App authorization expired or revoked.",
//   stack: "Error↵  at new a.Unauthorized (vendor.js:65710:41870)"
// }

But what I actually get is this:

![image](https://user-images.githubusercontent.com/73845971/119944023-adabaa00-bf8b-11eb-971f-1985cf5b3316.png)

Only tested with dropbox so far. Thanks

**Comment by raucao** [comment]
This could be a bug with the Dropbox back-end. Could you test this with the normal RS back-end as well perhaps?

Also, is the app using rs.js `1.2.3` or `2.0.0-beta.0` (or yet another version)?

**Comment by murphypetercl** [comment]
Thanks for the quick response. I'll try with 5apps. Is there a way to set a short expiry with 5apps do you know? The shortest option I can see seems to be 1 day. With Dropbox it is 4 hours.

I'm using the 2.0.0 beta.

**Comment by raucao** [comment]
Yes, I think 1 day is the shortest option.

**Comment by galfert** [comment]
Another way to trigger the error faster is to revoke the token in the 5apps interface.

**Comment by murphypetercl** [comment]
Cool thanks, I was able to simulate it that way. Getting the same error with 5apps though:

![image](https://user-images.githubusercontent.com/73845971/120008754-313cb980-bfd3-11eb-94de-a4531a280d7d.png)

**Comment by raucao** [comment]
Hmm, at first glance I cannot see how this could break. The widget, which is tested with the latest beta, uses the error's `name` property, and there's also a unit test for it in the WireClient test suite.

Are you sure it's not a problem with the logging somehow? What does `err.name` or `err.message` return in your code?

**Comment by murphypetercl** [comment]
Cool that has worked.

![image](https://user-images.githubusercontent.com/73845971/120096189-ed0bff00-c121-11eb-8dab-cea82c2b78b2.png)


![image](https://user-images.githubusercontent.com/73845971/120096202-fac18480-c121-11eb-8a89-2edbb8cbd403.png)

I guess the console output of the err object just threw me off. Maybe an idea to tweak the documentation to clarify how to use it.


This is a great library btw - really liking it.
