### ISSUE TITLE
Connect account with personal URL instead of user address

### ISSUE THREAD

**Issue by u0nel** [remotestorage/remotestorage.js#1247]
The spec allows to use an url as an user identifier, but if I try to login with my domain it says "user address doesn't contain an @"

**Comment by raucao** [comment]
Thanks. Could you perhaps provide the actual URL with associated Webfinger entry for me to test this (when changing the string validation)?

**Comment by raucao** [comment]
Thanks!

Just for reference: https://webfinger.net/lookup/?resource=https%3A%2F%2Fu1l.de

Might have to add support for URLs in [webfinger.js](https://github.com/silverbucket/webfinger.js), in case it's not there yet.

**Comment by galfert** [comment]
I just checked, webfinger.js supports URLs already.
