### ISSUE TITLE
ReferenceError: XMLHttpRequest is not defined when connecting with a token

### ISSUE THREAD

**Issue by bdashore3** [remotestorage/remotestorage.js#1253]
When I try connecting with a token to 5apps.com, I get an error that says `ReferenceError: XMLHttpRequest is not defined` and I'm not sure why this is happening.

Code:
```
const remoteStorage = new RemoteStorage();
remoteStorage.access.claim('*', 'rw');

remoteStorage.connect('username@5apps.com', 'token');
```

Error is attached below

[output.txt](https://github.com/remotestorage/remotestorage.js/files/7645514/output.txt)

**Comment by raucao** [comment]
It seems your trying this from node.js or a similar non-browser environment? If so, you may need a polyfill library for either `XMLHttpRequest` or `Fetch`.

**Comment by bdashore3** [comment]
How would this be implemented in typescript? The XMLHttpRequest library doesn't have any type defs on npm, so I get a bunch of errors

[https://www.npmjs.com/package/xmlhttprequest](https://www.npmjs.com/package/xmlhttprequest)

Here's my full typescript code

```
import RemoteStorage from 'remotestoragejs';

const remoteStorage = new RemoteStorage();
remoteStorage.access.claim('*', 'rw');

remoteStorage.connect('username@5apps.com', 'token');
```

**Comment by bdashore3** [comment]
Update: After some research, I was able to use isomorphic-fetch for the polyfill. Is there a simpler way to accomplish this, or did I do it right?

```ts
import 'isomorphic-fetch';

import RemoteStorage from 'remotestoragejs';

const remoteStorage = new RemoteStorage({ logging: true });
remoteStorage.access.claim('*', 'rw');

remoteStorage.connect('username@5apps.com', 'token');
```

**Comment by raucao** [comment]
Good question! We only moved to typescript with 2.0.0, which is why it's still officially a beta version.

Could you try https://www.npmjs.com/package/node-fetch instead?

rs.js supports both fetch and the older xmlhttprequest, and the node-fetch library comes with TS definitions bundled by default.

**Comment by bdashore3** [comment]
Using node-fetch did not work due to type errors when setting the global variable (didn't want to deal with that headache), so I opted to use cross-fetch instead, which is a better library with type defs.

Here's the code for anyone else who stumbles upon this issue:

```ts
import 'cross-fetch/polyfill';

import RemoteStorage from 'remotestoragejs';

const remoteStorage = new RemoteStorage({ logging: true });
remoteStorage.access.claim('*', 'rw');

// Replace with your token/username
remoteStorage.connect('username@5apps.com', 'token');
```

**Comment by raucao** [comment]
Great! I created an issue to document this properly.
