### ISSUE TITLE
hypercore, solid-project, webdav, ipfs or remote-storage?

### ISSUE THREAD

**Issue by codehangen** [remotestorage/remotestorage.js#1280]
Hi all.

*I would like to know at a technical level what is the difference between the remote-storage protocol and the solid-project, hypercore, webdav or ipfs protocol.*

**Comment by raucao** [comment]
Thanks for your question. However, this repository and its issues are for the remoteStorage.js JavaScript library, but not for general questions about Internet protocols.

For the remoteStorage protocol, please check out [this intro on the remoteStorage website] as well as the actual [draft specification](https://datatracker.ietf.org/doc/html/draft-dejong-remotestorage-19). You can also ask (hopefully more specific) questions on the [community forums](https://community.remotestorage.io/).
