### ISSUE TITLE
Tests fail under NodeJS v18

### ISSUE THREAD

**Issue by DougReeder** [remotestorage/remotestorage.js#1300]
Both the  `test` and `test:mocha` scripts fail under node 18 with the error: `ReferenceError: FileReader is not defined`

changing 
`if (typeof Blob === 'undefined') {`
to    `if (typeof Blob === 'undefined' || typeof FileReader === 'undefined') {`
at line 248 of `util.ts` fixes this for `test:mocha`, but then `test` throws 
```
UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "[object Object]".
```

**Comment by raucao** [comment]
I had a look at this, and it's actually just due to `Blob` having promoted to the global context in node 18, since it's not experimental anymore, and our code checks for Blob being available or not to determine if it should read the file using browser APIs or node.js ones. Fix incoming.
