### ISSUE TITLE
Where did the »4 minutes ago« indication of last sync go?

### ISSUE THREAD

**Issue by jancborchardt** [remotestorage/remotestorage.js#421]
There used to be a short indication of when the last sync run was. It’s not there anymore. What happened @nilclass @michielbdejong?

Thinking about it, I actually like it better without it. Not really sure what purpose it served anyway, since it should always be in sync. So not something to fix, I just want to know if this was a decision or if it just went missing at some point. :)

**Comment by skddc** [comment]
Re-implemented (albeit a bit different) in the new widget.
