### ISSUE TITLE
dropbox.js sharing

### ISSUE THREAD

**Issue by ggrin** [remotestorage/remotestorage.js#435]
the getItemURL function of baseclient shoudl return a shared url which we can ask for by dropbox.  This of course is asyncchronious. 
Therefor if the path is  some /public/\* and not cached before it gets fetcched.

But for some reason I don't understand this always finishes after the put promise returns(is fulfilled and the then block outside of dropbox part gets executed)

**Comment by galfert** [comment]
Replaced by issue #1052.
