### ISSUE TITLE
Allow stricter CSP by removing inline style

### ISSUE THREAD

**Issue by clochix** [remotestorage/remotestorage.js#463]
I'm trying to enforce the security of a website by using Content Security Policy (CSP).

To style the widget, the script create a `style` element and inject the content of `widgetCss.css` into it. This add an inline style to the page, so it only works if the CSP uses `style-src: 'unsafe-inline'`. Not a big deal but I would like to find another solution.

Maybe we could create a new `style` element only if current document has no stylesheets. If the document contains at least one sheet, we could add our rules to the last sheet with `insertRule` ( https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet.insertRule?redirectlocale=en-US&redirectslug=Web%2FAPI%2FCSSStyleSheet%2FinsertRule ). Unfortunately, this method is only available in IE ≥ 9.

Another solution would be to add a build option to not include `widgetCss.css` into the compiled source. With this option, the developer would have to copy the stylesheet into its website and link it from the page.

**Comment by skddc** [comment]
Closing in favor of new widget library, where no inline styles are used.
