### ISSUE TITLE
Add release to CDNJS

### ISSUE THREAD

**Issue by skddc** [remotestorage/remotestorage.js#467]
Apparently we did this before, so let's update it: http://cdnjs.com/libraries/remoteStorage/

**Comment by gunar** [comment]
Done with [commit on cdnjs/cdnjs](https://github.com/cdnjs/cdnjs/commit/d17d75696a9dc1461a132d852425b15515cff0c4).

I'll leave this open to check if the package will be successfully updated through npm.

**Comment by gunar** [comment]
RemoteStorage doesn't accept AGPL-3.0 anymore. I'll be pushing a new PR to cdnjs, but first let's see if it auto-updates correctly.

**Comment by skddc** [comment]
It's MIT actually.

**Comment by gunar** [comment]
Npm auto-update is working ([cdnjs/rs](http://cdnjs.com/libraries/remoteStorage)).
Licence is up-to-date ([commit](https://github.com/cdnjs/cdnjs/pull/6015#event-443586692)).

**Comment by skddc** [comment]
Is this linked somewhere, so people can find it?

**Comment by gunar** [comment]
Good point. I added it to Wiki/Beginner's Guide/Get remoteStorage.js.

**Comment by skddc** [comment]
Cool.
