### ISSUE TITLE
Make standard release AMD-compatible

### ISSUE THREAD

**Issue by xMartin** [remotestorage/remotestorage.js#582]
Currently you have to do your own build to create an AMD version of the library. Would be nice to make the standard release AMD-compatible.

See #443.

**Comment by skddc** [comment]
@silverbucket Do you know what to do here still? Would be great to remove the extra build there.

**Comment by silverbucket** [comment]
Hmm... I'm not sure anymore about what this bug is meant to do. Is it just to load the built rs.js library via. AMD? or is it to selectively load each of the separate files as they are needed? It's been so long I forgot everything around this that I was working on at the time. :/

**Comment by xMartin** [comment]
It's about loading the complete build as AMD module (see above).

**Comment by skddc** [comment]
Closing this in favor of #949 and @lesion's major layout refactoring, which already supports loading via all of AMD, ES6, global, et al.

**Comment by michielbdejong** [comment]
Great to see @xMartin's [advocacy from the very early days](https://github.com/remotestorage/remotestorage.js/pull/35) finally became a reality :)
