### ISSUE TITLE
thousands of AbortErrors when refreshing the page

### ISSUE THREAD

**Issue by michielbdejong** [remotestorage/remotestorage.js#592]
sometimes when you refresh the page, thousands of AbortErrors are fired from lines that read:

```
store.get(path).onsuccess = function(evt) {
```

in `src/indexeddb.js`

i'm not sure whether this is a problem but it seems to take up several minutes when the console is open (not sure how much time it takes up when the console is not open)

**Comment by untitaker** [comment]
I get the following console entries repeated ~100 times:

    AbortError all.js:11235:0  <= this line x 2000
    "[Widget] typeof this.rs.sync check fail" undefined all.js:3521:7
