### ISSUE TITLE
Review possible use of localForage

### ISSUE THREAD

**Issue by galfert** [remotestorage/remotestorage.js#606]
[localForage](https://github.com/mozilla/localForage) basically has the localStorage API, but it's asynchronous using either callbacks or promises. It uses IndexedDB or WebSQL as storage backend (or localStorage if nothing else works).

Since we don't have any WebSQL support yet, this library might be worth looking into.

**Comment by skddc** [comment]
If this is solely for storing settings, then I think localforage is too big of a cannon for shooting that bird. Also, we had some trouble with localforage in the wild in some of our commercial apps actually.

@galfert Was the proposal for all data, and do you still think it's a good idea to tie rs.js to localforage?

**Comment by skddc** [comment]
Ping @galfert

**Comment by galfert** [comment]
I didn't mean to only use it for the settings, but to replace our whole indexedDB & localStorage backend implementation.

I still think it's a good idea to at least investigate if that's a viable option.

**Comment by skddc** [comment]
That would mean tying an essential part of this library to a different one that a) we cannot control, b) we had issues with ourselves in the past and c) would add its whole size to our code size.

I'm not entirely sure what you mean by "investigate". Do you have concrete pointers for someone or yourself to  pick up this issue and do it right now? What are the questions we want to answer?

**Comment by skddc** [comment]
@galfert I think you missed my question here.

**Comment by galfert** [comment]
The only issue I can remember was that both remoteStorage and localForage came with conflicting Promise libraries, and using the localForage `nopromises` build fixed that.

I'm not sure of the overall size impact this would have, since we would also be able to delete a bunch of our own code. That's also what I mean by "investigate". But at the same time we would gain WebSQL support and replace some of our code that I myself am not too confident with (e.g. binary support) with a well-tested and maintained library.

That being said, I also think there are much more important issues. Like getting rid of the Bluebird dependency and using a more modern build system with proper ES6 support.

**Comment by galfert** [comment]
With Safari getting IndexedDB support pretty soon, I don't think this is not really worth to consider anymore.
