### ISSUE TITLE
spec modules pages return 404

### ISSUE THREAD

**Issue by maxlath** [remotestorage/remotestorage.js#618]
Exploring what litewrite generated with the [RS browser](https://github.com/nilclass/remotestorage-browser-example), I found the JSON-LD document model as such
`"@context": "http://remotestoragejs.com/spec/modules/documents/text"`
but http://remotestoragejs.com/spec/modules/documents/text returns a blank page with just a weird godaddy iframe in the code `<!DOCTYPE html><body style="padding:0; margin:0;"><iframe src="http://mcc.godaddy.com/park/MKW6LzqlMzqvMJ50paqzYaOvrt==?=404;http://remotestoragejs.com:80/spec/modules/documents/text" style="visibility: visible;height: 2000px;" allowtransparency="true" marginheight="0" marginwidth="0" frameborder="0" scrolling="no" width="100%"></iframe></body></html>`
Are those pages in the todo or is that a bug? (or do I get something wrong?)

**Comment by skddc** [comment]
Closing in favor of https://github.com/remotestorage/modules/issues/96 as it concerns data modules more than rs.js core.
