### ISSUE TITLE
Problems with remoteStorage.inspect()

### ISSUE THREAD

**Issue by galfert** [remotestorage/remotestorage.js#679]
When testing `remoteStorage.inspect()`, I saw some issues:
- When the inspector is injected into the DOM, it's partially overlapped by other elments (setting the z-index to a very high value fixed that)
- The main title overlaps with the title of the first table (Remote)
- The Content-Type contains the charset.
- The entries for local have no revision

![remotestorage inspect](https://cloud.githubusercontent.com/assets/843/3015003/12dcc5c8-df5e-11e3-9c47-15a8a93e7f67.png)

When talking with @skddc about this, he had the idea that it would probably better to create a proper dev tool extension for Browsers instead (starting with Firefox at first, because Chrome already has an inspector for IndexedDB). I like that idea as well.

**Comment by skddc** [comment]
Do we actually still ship the inspector?

**Comment by galfert** [comment]
The inspector doesn't exist anymore.
