### ISSUE TITLE
improve docs on keep/revert events

### ISSUE THREAD

**Issue by michielbdejong** [remotestorage/remotestorage.js#707]
specifically, the keep/revert events are introduced as if they are a thing; we should make it clear in the docs that this is a concept of our own invention. 

also, the text is a bit of an inaccessible wall of text.

**Comment by skddc** [comment]
@michielbdejong Not sure which docs exactly this is referring to. Could you explain/link plz?

**Comment by michielbdejong** [comment]
it referred to https://github.com/remotestorage/remotestorage.js/blob/master/doc/data-format.md#keeprevert-conflict-resolution, sorry

**Comment by skddc** [comment]
Ah, got it. Thanks!
