### ISSUE TITLE
As an app developer I want to know when syncing is done

### ISSUE THREAD

**Issue by xMartin** [remotestorage/remotestorage.js#732]
When syncing documents or initially loading documents there's single events for each new or updated document. If I use these events to update the UI lots of updates are made in a short time causing things to flicker or jump around in case of updated order in a list or something and it is also just inefficient. I would like to know when a sync cycle or an initial loading is done so I can use that event to trigger one single update of the UI with all the new data.

**Comment by skddc** [comment]
FYI: when `remoteStorage` is `ready`, there's `remoteStorage.sync.on('done')`. This will fire, when all single sync tasks have been completed and a new sync is queued. There's also `req-done` for the single tasks.

I think we should probably emit that event on the `remoteStorage` instance itself as well, in order for it to be a proper public event. Then again, maybe it's also nice to keep these things namespaced on the classes. Not sure. Any opinions?

**Comment by skddc** [comment]
In 1.0.x, there is now an event `sync-req-done` and `sync-done` for both the single sync operations as well as a whole cycle completing (i.e. everything has been synced according to the caching config): https://remotestoragejs.readthedocs.io/en/latest/js-api/remotestorage.html#list-of-events

Also, the [`startSync()`](https://remotestoragejs.readthedocs.io/en/latest/js-api/remotestorage.html#startSync) function will return a promise, which resolves after a successful sync. However, it's recommended to use the events, as the library automatically syncs changes, both on app startup as well as periodically after that.
