### ISSUE TITLE
Offline mode broken

### ISSUE THREAD

**Issue by xMartin** [remotestorage/remotestorage.js#740]
When I go offline the widget is not indicating offline state.

Broken in 0.10.0, works in 0.10.0-beta.

Tested with Work Offline in Firefox. Apps: Grouptabs, Sharesome (0.10.0) and Litewrite (0.10.0-beta).

**Comment by skddc** [comment]
This is (still?) broken in the latest stable release in FF for me. I have a feeling this never worked since Martin reported it.

**Comment by skddc** [comment]
Can someone please help verify this issue?

**Comment by skddc** [comment]
Ok, I tested in both FF and Chrome and the offline mode gets set correctly (`remoteStorage.remote.online` is set to `false` after failing requests and `true` again after the next successful one). However the widget offline state isn't set.

**Comment by skddc** [comment]
https://github.com/remotestorage/remotestorage.js/blob/master/src/widget.js#L194 is hit as well.

**Comment by xMartin** [comment]
Works for me in 0.11.2. Cool!

**Comment by skddc** [comment]
\o/
