### ISSUE TITLE
Use common base directory for all remoteStorage data

### ISSUE THREAD

**Issue by skddc** [remotestorage/remotestorage.js#796]
Currently the library is creating/using directories in the Dropbox root directory, which can easily caues conflicts with existing data, or new data stored by apps that don't use rs.js, as well as makes it hard for users to know where all their remoteStorage app data is stored. I'd propose to have either some kind of common root directory or some kind of prefix for RS categories.

Opinions?

**Comment by skddc** [comment]
Looks like we have consensus on this. @Ragnis Wanna go ahead and change it?

**Comment by Ragnis** [comment]
Okay, I'll try to get it done some time soon

**Comment by skddc** [comment]
Great!

**Comment by skddc** [comment]
@Ragnis Still want to do this? Would still be a good idea for Dropbox and bring it much closer to non-experimental status.

**Comment by Ragnis** [comment]
I think I might have some time this weekend to take a look at it.

**Comment by skddc** [comment]
I got Webmarks to work again (commenting out the browser_sync task in Gruntfile and using node 4.4).

Things seem to work okay. However, DELETEs are rejected and not even attempted:

![screenshot from 2016-06-24 12-04-43](https://cloud.githubusercontent.com/assets/842/16343317/62b01d2c-3a04-11e6-8a20-289af6d097cf.png)

@galfert @Ragnis Did you test deletes? Not sure if it's just me (and my shit connection on this Amtrak train), or a general bug with the new dir. It certainly does seem to be a path issue, judging from the logs.

**Comment by galfert** [comment]
I tested deleting entries, but only in Chrome and there it worked. Just tested again in Firefox and I'm getting the same error as you there.

**Comment by skddc** [comment]
So it still works in Chrome? Would be a weird thing for browser compat issues.

**Comment by galfert** [comment]
Yes, works in Chrome for me.

**Comment by galfert** [comment]
Implemented with #928.
