### ISSUE TITLE
Syntax error in minified build

### ISSUE THREAD

**Issue by xMartin** [remotestorage/remotestorage.js#817]
Safari throws an error using `remotestorage.min.js`:

     [Error] SyntaxError: Cannot declare a parameter named 'e' as it shadows the name of a strict mode function.

Version 0.11.0
Safari 7.1 (Mac OS 10.9.5) and Safari iOS 8

**Comment by skddc** [comment]
What happened to this one?

**Comment by galfert** [comment]
Discussion continued in https://github.com/remotestorage/remotestorage.js/pull/824.

**Comment by skddc** [comment]
Oh, right. Totally forgot about what happened exactly.
