### ISSUE TITLE
need to call remoteStorage.sync.sync() from remoteStorage.on('connected') in nodejs

### ISSUE THREAD

**Issue by michielbdejong** [remotestorage/remotestorage.js#820]
in the browser, remoteStorage.on('connected') happens before RemoteStorage.Sync._rs_init, but in nodejs this is not (necessarily) the case. That means [`numToHave` will be 0](https://github.com/remotestorage/remotestorage.js/blob/0.11.0/src/sync.js#L941) on the first sync run, and therefore 'done' is never emitted meaning the [code to schedule the next sync cycle](https://github.com/remotestorage/remotestorage.js/blob/0.11.0/src/sync.js#L1110-L1116) never gets called.

So in nodejs you need to call remoteStorage.sync.sync() explicitly once you receive the 'connected' event.

In the future it may make sense to emit 'done' when `numToHave` is zero, so that it checks every 10 seconds whether a remote was connected. Or if no remote is connected, register an event handler on the 'connected' event, to start sync as soon as a remote is connected

**Comment by galfert** [comment]
This was fixed with #930.
