### ISSUE TITLE
Fix docs reg. API/app keys

### ISSUE THREAD

**Issue by skddc** [remotestorage/remotestorage.js#850]
I just wanted to configure Dropbox for Webmarks, but hit a roadblock right away:

The docs state that you should only set one "api_key" (which, btw should probably be camelCase like all other config options). However, the Dropbox site has both an "app key" and "app secret" for my app, as well as an "access token", which I think is just a bearer token for my own account.

Can someone shine some light on this? @Ragnis maybe? Or @michielbdejong?

**Comment by michielbdejong** [comment]
I think there's a tool for converting them

**Comment by michielbdejong** [comment]
ah it's explained here: https://github.com/dropbox/dropbox-js/blob/stable/guides/getting_started.md#initialization

> If your JavaScript code runs on users' computers, do NOT expose your API secret in the code.
> ````js
> // Browser-side applications do not use the API secret.
> var client = new Dropbox.Client({ key: "your-key-here" });
> ````

**Comment by skddc** [comment]
So API key is just the app key then I guess?

**Comment by Ragnis** [comment]
Yes, you use the "app key". We should probably write that in the documentation, too.

**Comment by skddc** [comment]
Alright, thanks.

**Comment by skddc** [comment]
Renamed in https://github.com/remotestorage/remotestorage.js/commit/d8cf72fd5a01bd8302ab7e71324ceef1b755be05
