### ISSUE TITLE
FF not always sending If-None-Match headers

### ISSUE THREAD

**Issue by skddc** [remotestorage/remotestorage.js#860]
We have to investigate why that is. Reproducible e.g. in Webmarks for @galfert and me.

**Comment by skddc** [comment]
I think this turned out to be invalid, right @galfert?

**Comment by galfert** [comment]
No, I think that was #878.

**Comment by skddc** [comment]
Ah, thanks.

**Comment by skddc** [comment]
Closing this until we see it again. Haven't encountered it since then.
