### ISSUE TITLE
Will the Dropbox API deprecations affect this library?

### ISSUE THREAD

**Issue by skddc** [remotestorage/remotestorage.js#865]
I don't really know how we're using Dropbox in the experimental Dropbox feature, maybe @Ragnis you can tell if we have to migrate or not?

https://blogs.dropbox.com/developers/2015/04/deprecating-the-sync-and-datastore-apis/

**Comment by Ragnis** [comment]
Nothing needs to be done.

**Comment by skddc** [comment]
![iloveit](https://cloud.githubusercontent.com/assets/842/7615990/88e9a76e-f9a1-11e4-9e31-9234d84cdf66.gif)
