### ISSUE TITLE
Disconnecting without clearing local data?

### ISSUE THREAD

**Issue by lewisl9029** [remotestorage/remotestorage.js#866]
Disconnecting remotestorage right now seems to clear everything(?) in IndexedDB by default.

Is it possible to bypass this side-effect and just disconnect a remotestorage account without clearing IndexedDB? For apps that create local modules for offline use and then optionally allow the user to connect a remotestorage account to selectively sync all or none of them, this behavior can be problematic because it happens to remove unsync'd, offline-only modules and modules used by different remotestorage accounts on disconnect as well.

I'm also wondering why this is the default behavior to begin with. On disconnecting a remotestorage account, I think it'd be more reasonable to by default only clear local cache for modules that have been claimed for access in that account.

Any thoughts?

**Comment by lewisl9029** [comment]
Also, I'm wondering if there's a way to claim access for additional modules and ask users for authorization without having to disconnect and reconnect.

**Comment by skddc** [comment]
> Also, I'm wondering if there's a way to claim access for additional modules and ask users for authorization without having to disconnect and reconnect.

There's no special way for that defined in the protocol. The authorization part is just OAuth, so anything that is possible with the OAuth redirect flow is possible with remoteStorage.

With remoteStorage.js, if I'm not mistaken, the widget will currently ask the user to re-auth, but not disconnect them completely.

**Comment by skddc** [comment]
Regarding clearing the cache when disconnecting: currently it is only possible to clear everything, because the library doesn't support using multiple instances of remoteStorage in parallel *yet*. We're actually going to have to implement that in a future version, because we'll need it in [Kosmos](https://kosmos.org) at some point. Probably more towards the end of the year, though.

Without support for multiple instances, there's no way to know what data belongs to which one. You can only write something if you claim access for it, no matter if you then connect an account or not. The connecting a remote storage is entirely optional and basically just mirrors what you have stored locally (not 100% accurate from a code perspective, but that's the overall concept of it).

Does that make sense to you?

**Comment by lewisl9029** [comment]
Yes that all made sense. Thanks for the clarification.

So it's not possible to clear only part of the cache at the moment, but would it be possible in the mean time to simply offer the option to not clear the IndexedDB data at all on disconnect? And allow the app itself to handle any necessary cleanup in a more granular manner?

**Comment by skddc** [comment]
I believe it is usually expected that an app removes your data from the device when you disconnect your storage. What would be the use case in your app? (I.e. why would you want to keep data, even when the user basically says "log me out of this app"?

**Comment by lewisl9029** [comment]
The use case I'm trying to accomplish is to have multiple app accounts, each associated with a specific remotestorage account, or no remotestorage accounts at all (for local-only app accounts). Right now, disconnecting a remotestorage account clears all app accounts, even the ones that are local-only or associated with another remotestorage account, which is definitely not the behavior users would expect in such a setup. 

I'm thinking of an implementation involving the following modules:
appId + '-account-' + accountId
-Contains account specific user data
appId + '-accounts-' + remotestorageId
-Contains a list of app account ids associated with a remotestorage account

Having the ability to not automatically delete all data on disconnect will allow the app to use metadata not available to remotestorage to implement its own, more granular cleanup procedure on disconnect as a workaround (say removing only the appId + '-account-' + accountId modules for ids listed in the appId + '-accounts-' + remotestorageId module), at least until we have proper native support for multi-instance in remotestorage itself.

**Comment by skddc** [comment]
I think the only clean way of doing this is adding native support for multiple instances to remoteStorage.js. You can hack the library to override [the disconnect function](https://github.com/remotestorage/remotestorage.js/blob/master/src/remotestorage.js#L366-L404) if you want to, but it's going to be error-prone and hard to upgrade, I'm afraid.

**Comment by lewisl9029** [comment]
I ended up doing a refactoring of the app to remove the multi-account functionality and go with single account per instance for now. It was already adding a lot of complexity without much benefit since users could just open a different browser or use private browsing features to switch accounts anyways. 

Might consider adding it back in eventually after remoteStorage gets proper multi-instance support rather than fighting the library to get it in now. Thanks for the help! =)

**Comment by skddc** [comment]
Glad I could help. I think that's the best route to take for now.
