### ISSUE TITLE
Initial PUTs missing `If-None-Match: *`?

### ISSUE THREAD

**Issue by skddc** [remotestorage/remotestorage.js#878]
We just realized that it's possible to just overwrite things that exist but haven't been fetched yet by default. The PUT requests seem to be missing the If-None-Match wildcard value which is explicitly mentioned in https://tools.ietf.org/html/draft-dejong-remotestorage-02#section-12.5

**Comment by galfert** [comment]
According to this line it should actually set the `If-None-Match` header: https://github.com/remotestorage/remotestorage.js/blob/master/src/sync.js#L348

Trying to investigate why it's not happening.

**Comment by galfert** [comment]
This was an error in our app. I did not define the `storageApi` when calling `remoteStorage.remote.configure()`. Thus the library assumed the storage server wouldn't support revisions and omitted the `If-None-Match` header.

**Comment by skddc** [comment]
Good catch! Also, nice selfpwn by using internal APIs in our app. :)

![selfpwn](https://cloud.githubusercontent.com/assets/842/9386971/75a863b0-475e-11e5-870d-b737747db412.gif)
