### ISSUE TITLE
Two change events for the same change

### ISSUE THREAD

**Issue by galfert** [remotestorage/remotestorage.js#879]
For a single remote change, there are two change events coming in. The second event's `oldValue` and `newValue` are the same though.

**Comment by skddc** [comment]
Note: not confirmed to be a library problem necessarily.

**Comment by skddc** [comment]
@galfert Did you follow up on this?

**Comment by skddc** [comment]
@galfert Ping.

**Comment by galfert** [comment]
Can't see the problem anymore. So looks like it wasn't the libraries fault.
