### ISSUE TITLE
Widget: Disabled submit button when account field completed by browser

### ISSUE THREAD

**Issue by untitaker** [remotestorage/remotestorage.js#884]
When I focus the account input field, Firefox suggests my accountname. When I select that accountname, I can't just hit the small arrow to submit the form, I have to do bogus keystrokes such that the submit button becomes clickable.

**Comment by skddc** [comment]
See also https://github.com/remotestorage/remotestorage.js/issues/795#issuecomment-98889651 and https://github.com/remotestorage/remotestorage.js/issues/862 regarding the new widget, which will fix this soon.

**Comment by skddc** [comment]
Closing in favor of new-widget implementation.
