### ISSUE TITLE
Sync doesn't start automatically after calling `configure` with token

### ISSUE THREAD

**Issue by skddc** [remotestorage/remotestorage.js#885]
There's an issue left with the Cordova integration, which is that sync doesn't start automatically. Also, @galfert and I saw a similar issue with an app outside of Cordova as well.

https://github.com/remotestorage/remotestorage.js/blob/master/src/authorize.js#L52-L55

**Comment by skddc** [comment]
I think we can close this, since we merged #930, right @galfert?

**Comment by galfert** [comment]
Yes, this should be fixed now.

**Comment by skddc** [comment]
Hooray! (and /cc @lewisl9029)

![thumbs-up-daft-punk](https://cloud.githubusercontent.com/assets/842/15427124/262a5d4a-1e93-11e6-90e6-e8af91ee003c.gif)
