### ISSUE TITLE
Caching usability and handling of empty paths

### ISSUE THREAD

**Issue by untitaker** [remotestorage/remotestorage.js#888]
I found the following line in your HelloWorld example:

    privateClient.cache("")

https://github.com/remotestorage/starter-kit/blob/master/apps/hello-world/notes.js

The `cache` method isn't documented, so I removed it and naively switched to:

    privateClient.storage.caching.enable("")

However, I didn't know that this cache interface wasn't relative to the client's root. In addition to making remoteStorage try to cache the universe, this line also made it send requests to the storage root without a trailing slash, which violates the spec.

**Comment by skddc** [comment]
These lines are both weird. Are you referring to https://github.com/remotestorage/starter-kit maybe?

**Comment by untitaker** [comment]
Exactly, I've linked a file from that repo in the OP. It's on the second line.

**Comment by skddc** [comment]
Ah, missed it last night.

The starter kit has not really been peer-reviewed or maintained by the current rs.js core team. The normal method is `remoteStorage.caching.enable('/my-category/subdir/')` which makes it more obvious that it's relative to root. I've never even seen caching methods on the client I think. :)

It's documented here, but examples for `enable` are missing, and docs are sparse in general: https://remotestorage.io/doc/code/files/caching-js.html#RemoteStorage.Caching

I started a new guide on the wiki yesterday, which -- ideally with the help of you and others -- eventually I'd like to turn into the go-to resource for learning about the general usage of remoteStorage.js. In the end, it should describe every step of the way, including caching, conflict handling and all (maybe some of it on seperate pages, of course, but linked from there).

**Comment by untitaker** [comment]
What about the undocumented client method I used? It seemed to work fine, and yet, if it isn't documented perhaps it should be removed?

On 12 September 2015 12:26:21 CEST, Sebastian Kippe <notifications@github.com> wrote:
>Ah, missed it last night.
>
>The starter kit has not really been peer-reviewed or maintained by the
>current rs.js core team. The normal method is
>`remoteStorage.caching.enable('/my-category/subdir/')` which makes it
>more obvious that it's relative to root. I've never even seen caching
>methods on the client I think. :)
>
>It's documented here, but examples for `enable` are missing, and docs
>are sparse in general:
>https://remotestorage.io/doc/code/files/caching-js.html#RemoteStorage.Caching
>
>I started a new guide on the wiki yesterday, which -- ideally with the
>help of you and others -- eventually I'd like to turn into the go-to
>resource for learning about the general usage of remoteStorage.js. In
>the end, it should describe every step of the way, including caching,
>conflict handling and all (maybe some of it on seperate pages, of
>course, but linked from there).
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/remotestorage/remotestorage.js/issues/888#issuecomment-139747441

-- 
Sent from my phone. Please excuse my brevity.

**Comment by untitaker** [comment]
Additionally the caching object should reject an empty string if it leads to the client sending invalid requests, or automatically correct it.

On 12 September 2015 14:00:57 CEST, Markus Unterwaditzer <markus@unterwaditzer.net> wrote:
>What about the undocumented client method I used? It seemed to work
>fine, and yet, if it isn't documented perhaps it should be removed?
>
>On 12 September 2015 12:26:21 CEST, Sebastian Kippe
><notifications@github.com> wrote:
>>Ah, missed it last night.
>>
>>The starter kit has not really been peer-reviewed or maintained by the
>>current rs.js core team. The normal method is
>>`remoteStorage.caching.enable('/my-category/subdir/')` which makes it
>>more obvious that it's relative to root. I've never even seen caching
>>methods on the client I think. :)
>>
>>It's documented here, but examples for `enable` are missing, and docs
>>are sparse in general:
>>https://remotestorage.io/doc/code/files/caching-js.html#RemoteStorage.Caching
>>
>>I started a new guide on the wiki yesterday, which -- ideally with the
>>help of you and others -- eventually I'd like to turn into the go-to
>>resource for learning about the general usage of remoteStorage.js. In
>>the end, it should describe every step of the way, including caching,
>>conflict handling and all (maybe some of it on seperate pages, of
>>course, but linked from there).
>>
>>---
>>Reply to this email directly or view it on GitHub:
>>https://github.com/remotestorage/remotestorage.js/issues/888#issuecomment-139747441

-- 
Sent from my phone. Please excuse my brevity.

**Comment by skddc** [comment]
> What about the undocumented client method I used? It seemed to work fine, and yet, if it isn't documented perhaps it should be removed?

If it exists, then that's a private method and shouldn't be used from an app.

> Additionally the caching object should reject an empty string if it leads to the client sending invalid requests, or automatically correct it.

If you're talking about `caching.enable`, then you could add it here: https://github.com/remotestorage/remotestorage.js/blob/master/src/caching.js#L53-L55 -- I just checked real quick and `enable` is only a shorthand for `caching.set('mydir', 'ALL')`.

Weirdly enough, not only is it not checking empty strings, but it's also not checking if the string is a directory or not. Also, when I set wrong paths manually and then manually called `caching.reset()`, that removed the paths from `caching._rootPaths`, but it didn't stop invalid requests to the base URL (without the trailing slash) of my storage account.

**Comment by untitaker** [comment]
> If it exists, then that's a private method and shouldn't be used from an app.

Does it make sense if I propose that private properties should be prefixed with
an underscore? I think that would make it clearer that those aren't really part
of the API, especially when reading code that relies on them anyway.

> 
> > Additionally the caching object should reject an empty string if it leads
> > to the client sending invalid requests, or automatically correct it.
> 
> If you're talking about `caching.enable`, then you could add it here:
> https://github.com/remotestorage/remotestorage.js/blob/master/src/caching.js#L53-L55
> -- I just checked real quick and `enable` is only a shorthand for
> `caching.set('mydir', 'ALL')`.
> 
> Weirdly enough, not only is it not checking empty strings, but it's also not
> checking if the string is a directory or not. Also, when I set wrong paths
> manually and then manually called `caching.reset()`, that removed the paths
> from `caching._rootPaths`, but it didn't stop invalid requests to the base
> URL (without the trailing slash) of my storage account.

How would I check whether it is a valid path? Just `value.endsWith("/")`, or do
we want to rule out non-existing ones?

**Comment by skddc** [comment]
> Does it make sense if I propose that private properties should be prefixed with an underscore? I think that would make it clearer that those aren't really part of the API, especially when reading code that relies on them anyway.

Some of them are already prefixed with underscores. In general, the documentation should make that clear (if it's undocumented it's 99% not public), and when we switch to converting the source to ES6 in the near future, we can use actual private properties in JavaScript. So, I don't think it's worth rewriting all of the current source code at the moment. (Although if you want to do it, PRs are of course more than welcome).

> How would I check whether it is a valid path? Just `value.endsWith("/")`, or do we want to rule out non-existing ones?

Yes, you can use the `isFolder` util function for that, like in other src files/classes. See https://github.com/remotestorage/remotestorage.js/blob/master/src/cachinglayer.js#L15 for example.

Ideally, this would take into account if there was even access claimed for the path, and then complain to the developer accordingly. But any more validation than there currently is will be a very useful change, of course! The paths for which access is claimed are stored in `remoteStorage.access.rootPaths`.

**Comment by untitaker** [comment]
There are unittests that seem to assert that setting caching attributes works on files too. Are those just missing slashes?

**Comment by untitaker** [comment]
Also this is kinda funky (testbuild from master): https://travis-ci.org/remotestorage/remotestorage.js#L169

**Comment by untitaker** [comment]
@skddc Is it OK if I file a separate PR for adding a `make test`? Or is that file just for releases.

**Comment by skddc** [comment]
`npm test` already works and is aliased to the actual `jaribu` command. Feel free to add `make test` in the same way and open a PR.

**Comment by untitaker** [comment]
>Btw, I started a new guide on the wiki yesterday, which -- ideally with the help of you and others -- eventually I'd like to turn into the go-to resource for learning about the general usage of remoteStorage.js. In the end, it should describe every step of the way, including caching, conflict handling and all. Maybe some of it on seperate pages, of course, but linked from there. (So far, it only contains some notes I took during debugging sth.)

I think for now the biggest problem is that the API docs are sparse and incomplete.

**Comment by skddc** [comment]
Yes, that too. But the API docs are also pretty hard to understand when you don't know how all of it plays together and what it does in the first place. Both a general overview as well as the actual API docs are a still problem I think.

**Comment by skddc** [comment]
@untitaker IIRC you actually fixed the caching function accpeting empty strings and non-dir paths, right?

**Comment by untitaker** [comment]
Oh, yeah. I think this is fixed.
