### ISSUE TITLE
Should warn about apps having a root path != "/"

### ISSUE THREAD

**Issue by untitaker** [remotestorage/remotestorage.js#913]
Apps are expected to be hosted on their own subdomain. This requirement will be clarified as part of https://github.com/remotestorage/spec/issues/104 and https://github.com/remotestorage/spec/issues/101, however, it's up to the actual app developer to fulfill that requirement.

I don't expect app developers to read the specification, which is why remoteStorage.js should warn them about this kind of thing in the console.

**Comment by skddc** [comment]
How could the library know where the app's root is at?

I think adding this information to the docs is easier, as you can't develop an app without reading at least *some* of them. For example the [Beginner's Guide](https://wiki.remotestorage.io/RemoteStorage.js:Beginners'_Guide) (WIP). (Maybe add a bit about deployment/hosting.)

**Comment by untitaker** [comment]
I can assure you that a simple paragraph will be ignored.

>How could the library know where the app's root is at?

This is what I was getting at yesterday in IRC. Possible solution would be to require specification of app root in app code.

**Comment by skddc** [comment]
> I can assure you that a simple paragraph will be ignored.

>> Maybe add a bit about deployment/hosting

I think if we put something about how to deploy/host your app in the Beginner's Guide, it won't just be overlooked by default.

> Possible solution would be to require specification of app root in app code.

But that's unnecessary for basically everything but this very problem. It'd be a superfluous config that would only exist to tell you how to deploy your app. No?

**Comment by untitaker** [comment]
Well, yeah, but the problem is that apps running on a subpath work *too well*. Apart from "correctness", the dev has no reason to fix their broken deployment, because auth works, sync works, the app "works".

**Comment by skddc** [comment]
@untitaker Do you still think this should be baked into the library as opposed to going in the wiki/docs?

**Comment by untitaker** [comment]
I don't really know. I think the problem is real, but the proposed solution is impractical. Perhaps we can revisit this sometime when we require the app root for other things.

**Comment by skddc** [comment]
I added a new page for app developers to the RS wiki: https://wiki.remotestorage.io/App_Development:_Tips_and_Considerations

It's linked from another new page I created: https://wiki.remotestorage.io/Developer_Portal

Let's add more content to those, as we need to move it from the current website anyway. Also, the tips & considerations page would be interesting not just to RS app developers, but unhosted/JS app developers in general I think.
