### ISSUE TITLE
Replace bluebird with a simpler Promise polyfill

### ISSUE THREAD

**Issue by jorinvo** [remotestorage/remotestorage.js#917]
Bluebird is huge.
I tried using a different promise polyfill and everything still works.
Seems like there are no special bluebird features used anywhere...
I safed 60kb _minified_ with this.

Also, the promise lib shouldn't be a hard dependency, because many users already include some polyfill anyway. 
Just tell the user that you use the global Promise and for old browsers the user needs a polyfill.

I used this one: https://github.com/jakearchibald/es6-promise

**Comment by skddc** [comment]
Good idea.

We'll have to change some code however, as we currently use deferred objects quite a lot. Unfortunately,`Promise.defer` is now obsolete (and non-standard) and needs to be replaced in order to use vanilla Promises.

**Comment by jorinvo** [comment]
@skddc I think RS already includes a version of defer: https://github.com/remotestorage/remotestorage.js/blob/master/src/remotestorage.js#L4

**Comment by skddc** [comment]
Oh wow, totally missed that. No changes needed then. :)

**Comment by silverbucket** [comment]
Yeah - defer was obsoleted as a build-in method, but it's easy for us to
just make our own. So that should be fine. +1 on removing bluebird.

**Comment by gunar** [comment]
Good idea. Agreed.

**Comment by jorinvo** [comment]
The only thing we  need to do is to decide if we want to bundle a Promise polyfill or tell the user to include one ...

**Comment by galfert** [comment]
[localForage](https://github.com/mozilla/localForage) for example offers two separate builds. One with a bundled Promise polyfill (default) and one without. See (https://github.com/mozilla/localForage/tree/master/dist.

I think that's a good approach.

**Comment by skddc** [comment]
... except we didn't notice that when using it, and when it shat all over our parade, it took an annoying debugging session to find out why. So the approach is demonstrably not that good after all; at least in terms of execution with that lib.

**Comment by jorinvo** [comment]
I would tend to not include it. 
Promises [are coming](http://caniuse.com/#search=promise) to the browsers anyway and compared to the rest of setting up RS for an app, including a promise polyfill is pretty simple.
We can just add a one-liner to the instructions with a recommended polyfill lib.

**Comment by skddc** [comment]
We could also at least throw a human-readable warning when `Promise` is not defined, and tell developers that way (maybe with a link to the docs).

**Comment by galfert** [comment]
First step would be to get rid of the deprecated `deferred` usage.

**Comment by skddc** [comment]
@galfert @lesion What's the status of this in `master` now?

**Comment by galfert** [comment]
AFAIK there is no Bluebird and also no `deferred` calls anymore. So this issue can be closed.

**Comment by skddc** [comment]
But that means that one has to include a Promise library if they use rs.js and want to support older browsers, right? (I.e. we have to document that fact.)

**Comment by galfert** [comment]
Correct. I added [a note](https://github.com/remotestorage/remotestorage.js/issues/972#issuecomment-298044344) about that in the [documentation issue](https://github.com/remotestorage/remotestorage.js/issues/972).

**Comment by skddc** [comment]
Cool.
