### ISSUE TITLE
undefined: TypeError: null is not an object (evaluating 'localStorage.length')

### ISSUE THREAD

**Issue by skddc** [remotestorage/remotestorage.js#922]
Found this in a production app of ours. Looks like the localStorage detection needs even more bulletproofing.

**Comment by skddc** [comment]
Browser distribution:

<table class="table table-striped" data-reactid=".0.2.2.1.0.0.1.2"><thead data-reactid=".0.2.2.1.0.0.1.2.0"><tr data-reactid=".0.2.2.1.0.0.1.2.0.0"><th style="width:30px;" data-reactid=".0.2.2.1.0.0.1.2.0.0.0">%</th><th data-reactid=".0.2.2.1.0.0.1.2.0.0.1">Value</th><th style="width:200px;" data-reactid=".0.2.2.1.0.0.1.2.0.0.2">Last Seen</th></tr></thead><tbody data-reactid=".0.2.2.1.0.0.1.2.1"><tr data-reactid=".0.2.2.1.0.0.1.2.1.$0"><td class="bar-cell" data-reactid=".0.2.2.1.0.0.1.2.1.$0.0"><span class="bar" style="width:0.36%;" data-reactid=".0.2.2.1.0.0.1.2.1.$0.0.0"></span><span class="label" data-reactid=".0.2.2.1.0.0.1.2.1.$0.0.1"><span data-reactid=".0.2.2.1.0.0.1.2.1.$0.0.1.0">0.36</span><span data-reactid=".0.2.2.1.0.0.1.2.1.$0.0.1.1">%</span></span></td><td data-reactid=".0.2.2.1.0.0.1.2.1.$0.1"><a class="" href="/ilpt-gmbh/mobile-web-client/?query=browser%3A%22Chromium%2018.0%22" data-reactid=".0.2.2.1.0.0.1.2.1.$0.1.0">Chromium 18.0</a></td><td data-reactid=".0.2.2.1.0.0.1.2.1.$0.2"><time datetime="2016-01-11T16:32:59.000Z" title="January 11, 2016 4:32 PM UTC" data-reactid=".0.2.2.1.0.0.1.2.1.$0.2.0">4 days ago</time></td></tr><tr data-reactid=".0.2.2.1.0.0.1.2.1.$1"><td class="bar-cell" data-reactid=".0.2.2.1.0.0.1.2.1.$1.0"><span class="bar" style="width:1.45%;" data-reactid=".0.2.2.1.0.0.1.2.1.$1.0.0"></span><span class="label" data-reactid=".0.2.2.1.0.0.1.2.1.$1.0.1"><span data-reactid=".0.2.2.1.0.0.1.2.1.$1.0.1.0">1.45</span><span data-reactid=".0.2.2.1.0.0.1.2.1.$1.0.1.1">%</span></span></td><td data-reactid=".0.2.2.1.0.0.1.2.1.$1.1"><a class="" href="/ilpt-gmbh/mobile-web-client/?query=browser%3A%22Firefox%2031.0%22" data-reactid=".0.2.2.1.0.0.1.2.1.$1.1.0">Firefox 31.0</a></td><td data-reactid=".0.2.2.1.0.0.1.2.1.$1.2"><time datetime="2016-01-15T12:48:34.000Z" title="January 15, 2016 12:48 PM UTC" data-reactid=".0.2.2.1.0.0.1.2.1.$1.2.0">6 hours ago</time></td></tr><tr data-reactid=".0.2.2.1.0.0.1.2.1.$2"><td class="bar-cell" data-reactid=".0.2.2.1.0.0.1.2.1.$2.0"><span class="bar" style="width:0.36%;" data-reactid=".0.2.2.1.0.0.1.2.1.$2.0.0"></span><span class="label" data-reactid=".0.2.2.1.0.0.1.2.1.$2.0.1"><span data-reactid=".0.2.2.1.0.0.1.2.1.$2.0.1.0">0.36</span><span data-reactid=".0.2.2.1.0.0.1.2.1.$2.0.1.1">%</span></span></td><td data-reactid=".0.2.2.1.0.0.1.2.1.$2.1"><a class="" href="/ilpt-gmbh/mobile-web-client/?query=browser%3A%22Firefox%2040.0%22" data-reactid=".0.2.2.1.0.0.1.2.1.$2.1.0">Firefox 40.0</a></td><td data-reactid=".0.2.2.1.0.0.1.2.1.$2.2"><time datetime="2016-01-10T14:06:57.000Z" title="January 10, 2016 2:06 PM UTC" data-reactid=".0.2.2.1.0.0.1.2.1.$2.2.0">5 days ago</time></td></tr><tr data-reactid=".0.2.2.1.0.0.1.2.1.$3"><td class="bar-cell" data-reactid=".0.2.2.1.0.0.1.2.1.$3.0"><span class="bar" style="width:0.36%;" data-reactid=".0.2.2.1.0.0.1.2.1.$3.0.0"></span><span class="label" data-reactid=".0.2.2.1.0.0.1.2.1.$3.0.1"><span data-reactid=".0.2.2.1.0.0.1.2.1.$3.0.1.0">0.36</span><span data-reactid=".0.2.2.1.0.0.1.2.1.$3.0.1.1">%</span></span></td><td data-reactid=".0.2.2.1.0.0.1.2.1.$3.1"><a class="" href="/ilpt-gmbh/mobile-web-client/?query=browser%3A%22Chrome%20Mobile%2035.0%22" data-reactid=".0.2.2.1.0.0.1.2.1.$3.1.0">Chrome Mobile 35.0</a></td><td data-reactid=".0.2.2.1.0.0.1.2.1.$3.2"><time datetime="2016-01-06T10:30:16.000Z" title="January 6, 2016 10:30 AM UTC" data-reactid=".0.2.2.1.0.0.1.2.1.$3.2.0">9 days ago</time></td></tr><tr data-reactid=".0.2.2.1.0.0.1.2.1.$4"><td class="bar-cell" data-reactid=".0.2.2.1.0.0.1.2.1.$4.0"><span class="bar" style="width:0.36%;" data-reactid=".0.2.2.1.0.0.1.2.1.$4.0.0"></span><span class="label" data-reactid=".0.2.2.1.0.0.1.2.1.$4.0.1"><span data-reactid=".0.2.2.1.0.0.1.2.1.$4.0.1.0">0.36</span><span data-reactid=".0.2.2.1.0.0.1.2.1.$4.0.1.1">%</span></span></td><td data-reactid=".0.2.2.1.0.0.1.2.1.$4.1"><a class="" href="/ilpt-gmbh/mobile-web-client/?query=browser%3A%22Safari%206.1%22" data-reactid=".0.2.2.1.0.0.1.2.1.$4.1.0">Safari 6.1</a></td><td data-reactid=".0.2.2.1.0.0.1.2.1.$4.2"><time datetime="2016-01-04T14:04:24.000Z" title="January 4, 2016 2:04 PM UTC" data-reactid=".0.2.2.1.0.0.1.2.1.$4.2.0">11 days ago</time></td></tr><tr data-reactid=".0.2.2.1.0.0.1.2.1.$5"><td class="bar-cell" data-reactid=".0.2.2.1.0.0.1.2.1.$5.0"><span class="bar" style="width:5.07%;" data-reactid=".0.2.2.1.0.0.1.2.1.$5.0.0"></span><span class="label" data-reactid=".0.2.2.1.0.0.1.2.1.$5.0.1"><span data-reactid=".0.2.2.1.0.0.1.2.1.$5.0.1.0">5.07</span><span data-reactid=".0.2.2.1.0.0.1.2.1.$5.0.1.1">%</span></span></td><td data-reactid=".0.2.2.1.0.0.1.2.1.$5.1"><a class="" href="/ilpt-gmbh/mobile-web-client/?query=browser%3A%22Mobile%20Safari%208.0%22" data-reactid=".0.2.2.1.0.0.1.2.1.$5.1.0">Mobile Safari 8.0</a></td><td data-reactid=".0.2.2.1.0.0.1.2.1.$5.2"><time datetime="2016-01-11T18:03:13.000Z" title="January 11, 2016 6:03 PM UTC" data-reactid=".0.2.2.1.0.0.1.2.1.$5.2.0">4 days ago</time></td></tr><tr data-reactid=".0.2.2.1.0.0.1.2.1.$6"><td class="bar-cell" data-reactid=".0.2.2.1.0.0.1.2.1.$6.0"><span class="bar" style="width:2.54%;" data-reactid=".0.2.2.1.0.0.1.2.1.$6.0.0"></span><span class="label" data-reactid=".0.2.2.1.0.0.1.2.1.$6.0.1"><span data-reactid=".0.2.2.1.0.0.1.2.1.$6.0.1.0">2.54</span><span data-reactid=".0.2.2.1.0.0.1.2.1.$6.0.1.1">%</span></span></td><td data-reactid=".0.2.2.1.0.0.1.2.1.$6.1"><a class="" href="/ilpt-gmbh/mobile-web-client/?query=browser%3A%22Android%204.3%22" data-reactid=".0.2.2.1.0.0.1.2.1.$6.1.0">Android 4.3</a></td><td data-reactid=".0.2.2.1.0.0.1.2.1.$6.2"><time datetime="2016-01-02T12:09:18.000Z" title="January 2, 2016 12:09 PM UTC" data-reactid=".0.2.2.1.0.0.1.2.1.$6.2.0">13 days ago</time></td></tr><tr data-reactid=".0.2.2.1.0.0.1.2.1.$7"><td class="bar-cell" data-reactid=".0.2.2.1.0.0.1.2.1.$7.0"><span class="bar" style="width:1.09%;" data-reactid=".0.2.2.1.0.0.1.2.1.$7.0.0"></span><span class="label" data-reactid=".0.2.2.1.0.0.1.2.1.$7.0.1"><span data-reactid=".0.2.2.1.0.0.1.2.1.$7.0.1.0">1.09</span><span data-reactid=".0.2.2.1.0.0.1.2.1.$7.0.1.1">%</span></span></td><td data-reactid=".0.2.2.1.0.0.1.2.1.$7.1"><a class="" href="/ilpt-gmbh/mobile-web-client/?query=browser%3A%22Safari%209.0%22" data-reactid=".0.2.2.1.0.0.1.2.1.$7.1.0">Safari 9.0</a></td><td data-reactid=".0.2.2.1.0.0.1.2.1.$7.2"><time datetime="2016-01-14T21:06:13.000Z" title="January 14, 2016 9:06 PM UTC" data-reactid=".0.2.2.1.0.0.1.2.1.$7.2.0">a day ago</time></td></tr><tr data-reactid=".0.2.2.1.0.0.1.2.1.$8"><td class="bar-cell" data-reactid=".0.2.2.1.0.0.1.2.1.$8.0"><span class="bar" style="width:3.26%;" data-reactid=".0.2.2.1.0.0.1.2.1.$8.0.0"></span><span class="label" data-reactid=".0.2.2.1.0.0.1.2.1.$8.0.1"><span data-reactid=".0.2.2.1.0.0.1.2.1.$8.0.1.0">3.26</span><span data-reactid=".0.2.2.1.0.0.1.2.1.$8.0.1.1">%</span></span></td><td data-reactid=".0.2.2.1.0.0.1.2.1.$8.1"><a class="" href="/ilpt-gmbh/mobile-web-client/?query=browser%3A%22IE%20Mobile%2011.0%22" data-reactid=".0.2.2.1.0.0.1.2.1.$8.1.0">IE Mobile 11.0</a></td><td data-reactid=".0.2.2.1.0.0.1.2.1.$8.2"><time datetime="2016-01-07T16:57:17.000Z" title="January 7, 2016 4:57 PM UTC" data-reactid=".0.2.2.1.0.0.1.2.1.$8.2.0">8 days ago</time></td></tr><tr data-reactid=".0.2.2.1.0.0.1.2.1.$9"><td class="bar-cell" data-reactid=".0.2.2.1.0.0.1.2.1.$9.0"><span class="bar" style="width:0.72%;" data-reactid=".0.2.2.1.0.0.1.2.1.$9.0.0"></span><span class="label" data-reactid=".0.2.2.1.0.0.1.2.1.$9.0.1"><span data-reactid=".0.2.2.1.0.0.1.2.1.$9.0.1.0">0.72</span><span data-reactid=".0.2.2.1.0.0.1.2.1.$9.0.1.1">%</span></span></td><td data-reactid=".0.2.2.1.0.0.1.2.1.$9.1"><a class="" href="/ilpt-gmbh/mobile-web-client/?query=browser%3A%22Firefox%20Mobile%2041.0%22" data-reactid=".0.2.2.1.0.0.1.2.1.$9.1.0">Firefox Mobile 41.0</a></td><td data-reactid=".0.2.2.1.0.0.1.2.1.$9.2"><time datetime="2015-12-28T07:27:51.000Z" title="December 28, 2015 7:27 AM UTC" data-reactid=".0.2.2.1.0.0.1.2.1.$9.2.0">18 days ago</time></td></tr><tr data-reactid=".0.2.2.1.0.0.1.2.1.$10"><td class="bar-cell" data-reactid=".0.2.2.1.0.0.1.2.1.$10.0"><span class="bar" style="width:1.45%;" data-reactid=".0.2.2.1.0.0.1.2.1.$10.0.0"></span><span class="label" data-reactid=".0.2.2.1.0.0.1.2.1.$10.0.1"><span data-reactid=".0.2.2.1.0.0.1.2.1.$10.0.1.0">1.45</span><span data-reactid=".0.2.2.1.0.0.1.2.1.$10.0.1.1">%</span></span></td><td data-reactid=".0.2.2.1.0.0.1.2.1.$10.1"><a class="" href="/ilpt-gmbh/mobile-web-client/?query=browser%3A%22Safari%208.0%22" data-reactid=".0.2.2.1.0.0.1.2.1.$10.1.0">Safari 8.0</a></td><td data-reactid=".0.2.2.1.0.0.1.2.1.$10.2"><time datetime="2016-01-05T21:59:39.000Z" title="January 5, 2016 9:59 PM UTC" data-reactid=".0.2.2.1.0.0.1.2.1.$10.2.0">10 days ago</time></td></tr><tr data-reactid=".0.2.2.1.0.0.1.2.1.$11"><td class="bar-cell" data-reactid=".0.2.2.1.0.0.1.2.1.$11.0"><span class="bar" style="width:0.36%;" data-reactid=".0.2.2.1.0.0.1.2.1.$11.0.0"></span><span class="label" data-reactid=".0.2.2.1.0.0.1.2.1.$11.0.1"><span data-reactid=".0.2.2.1.0.0.1.2.1.$11.0.1.0">0.36</span><span data-reactid=".0.2.2.1.0.0.1.2.1.$11.0.1.1">%</span></span></td><td data-reactid=".0.2.2.1.0.0.1.2.1.$11.1"><a class="" href="/ilpt-gmbh/mobile-web-client/?query=browser%3A%22Firefox%2036.0%22" data-reactid=".0.2.2.1.0.0.1.2.1.$11.1.0">Firefox 36.0</a></td><td data-reactid=".0.2.2.1.0.0.1.2.1.$11.2"><time datetime="2015-12-16T13:08:13.000Z" title="December 16, 2015 1:08 PM UTC" data-reactid=".0.2.2.1.0.0.1.2.1.$11.2.0">a month ago</time></td></tr><tr data-reactid=".0.2.2.1.0.0.1.2.1.$12"><td class="bar-cell" data-reactid=".0.2.2.1.0.0.1.2.1.$12.0"><span class="bar" style="width:0.36%;" data-reactid=".0.2.2.1.0.0.1.2.1.$12.0.0"></span><span class="label" data-reactid=".0.2.2.1.0.0.1.2.1.$12.0.1"><span data-reactid=".0.2.2.1.0.0.1.2.1.$12.0.1.0">0.36</span><span data-reactid=".0.2.2.1.0.0.1.2.1.$12.0.1.1">%</span></span></td><td data-reactid=".0.2.2.1.0.0.1.2.1.$12.1"><a class="" href="/ilpt-gmbh/mobile-web-client/?query=browser%3A%22Mobile%20Safari%207.0%22" data-reactid=".0.2.2.1.0.0.1.2.1.$12.1.0">Mobile Safari 7.0</a></td><td data-reactid=".0.2.2.1.0.0.1.2.1.$12.2"><time datetime="2015-12-16T07:07:15.000Z" title="December 16, 2015 7:07 AM UTC" data-reactid=".0.2.2.1.0.0.1.2.1.$12.2.0">a month ago</time></td></tr><tr data-reactid=".0.2.2.1.0.0.1.2.1.$13"><td class="bar-cell" data-reactid=".0.2.2.1.0.0.1.2.1.$13.0"><span class="bar" style="width:0.36%;" data-reactid=".0.2.2.1.0.0.1.2.1.$13.0.0"></span><span class="label" data-reactid=".0.2.2.1.0.0.1.2.1.$13.0.1"><span data-reactid=".0.2.2.1.0.0.1.2.1.$13.0.1.0">0.36</span><span data-reactid=".0.2.2.1.0.0.1.2.1.$13.0.1.1">%</span></span></td><td data-reactid=".0.2.2.1.0.0.1.2.1.$13.1"><a class="" href="/ilpt-gmbh/mobile-web-client/?query=browser%3A%22Android%204.0%22" data-reactid=".0.2.2.1.0.0.1.2.1.$13.1.0">Android 4.0</a></td><td data-reactid=".0.2.2.1.0.0.1.2.1.$13.2"><time datetime="2015-12-15T14:22:44.000Z" title="December 15, 2015 2:22 PM UTC" data-reactid=".0.2.2.1.0.0.1.2.1.$13.2.0">a month ago</time></td></tr><tr data-reactid=".0.2.2.1.0.0.1.2.1.$14"><td class="bar-cell" data-reactid=".0.2.2.1.0.0.1.2.1.$14.0"><span class="bar" style="width:0.36%;" data-reactid=".0.2.2.1.0.0.1.2.1.$14.0.0"></span><span class="label" data-reactid=".0.2.2.1.0.0.1.2.1.$14.0.1"><span data-reactid=".0.2.2.1.0.0.1.2.1.$14.0.1.0">0.36</span><span data-reactid=".0.2.2.1.0.0.1.2.1.$14.0.1.1">%</span></span></td><td data-reactid=".0.2.2.1.0.0.1.2.1.$14.1"><a class="" href="/ilpt-gmbh/mobile-web-client/?query=browser%3A%22Chrome%2033.0%22" data-reactid=".0.2.2.1.0.0.1.2.1.$14.1.0">Chrome 33.0</a></td><td data-reactid=".0.2.2.1.0.0.1.2.1.$14.2"><time datetime="2015-12-13T16:31:03.000Z" title="December 13, 2015 4:31 PM UTC" data-reactid=".0.2.2.1.0.0.1.2.1.$14.2.0">a month ago</time></td></tr><tr data-reactid=".0.2.2.1.0.0.1.2.1.$15"><td class="bar-cell" data-reactid=".0.2.2.1.0.0.1.2.1.$15.0"><span class="bar" style="width:1.81%;" data-reactid=".0.2.2.1.0.0.1.2.1.$15.0.0"></span><span class="label" data-reactid=".0.2.2.1.0.0.1.2.1.$15.0.1"><span data-reactid=".0.2.2.1.0.0.1.2.1.$15.0.1.0">1.81</span><span data-reactid=".0.2.2.1.0.0.1.2.1.$15.0.1.1">%</span></span></td><td data-reactid=".0.2.2.1.0.0.1.2.1.$15.1"><a class="" href="/ilpt-gmbh/mobile-web-client/?query=browser%3A%22Firefox%2042.0%22" data-reactid=".0.2.2.1.0.0.1.2.1.$15.1.0">Firefox 42.0</a></td><td data-reactid=".0.2.2.1.0.0.1.2.1.$15.2"><time datetime="2016-01-08T10:43:11.000Z" title="January 8, 2016 10:43 AM UTC" data-reactid=".0.2.2.1.0.0.1.2.1.$15.2.0">7 days ago</time></td></tr><tr data-reactid=".0.2.2.1.0.0.1.2.1.$16"><td class="bar-cell" data-reactid=".0.2.2.1.0.0.1.2.1.$16.0"><span class="bar" style="width:29.71%;" data-reactid=".0.2.2.1.0.0.1.2.1.$16.0.0"></span><span class="label" data-reactid=".0.2.2.1.0.0.1.2.1.$16.0.1"><span data-reactid=".0.2.2.1.0.0.1.2.1.$16.0.1.0">29.71</span><span data-reactid=".0.2.2.1.0.0.1.2.1.$16.0.1.1">%</span></span></td><td data-reactid=".0.2.2.1.0.0.1.2.1.$16.1"><a class="" href="/ilpt-gmbh/mobile-web-client/?query=browser%3A%22Mobile%20Safari%209.0%22" data-reactid=".0.2.2.1.0.0.1.2.1.$16.1.0">Mobile Safari 9.0</a></td><td data-reactid=".0.2.2.1.0.0.1.2.1.$16.2"><time datetime="2016-01-15T18:31:26.000Z" title="January 15, 2016 6:31 PM UTC" data-reactid=".0.2.2.1.0.0.1.2.1.$16.2.0">23 minutes ago</time></td></tr><tr data-reactid=".0.2.2.1.0.0.1.2.1.$17"><td class="bar-cell" data-reactid=".0.2.2.1.0.0.1.2.1.$17.0"><span class="bar" style="width:36.96%;" data-reactid=".0.2.2.1.0.0.1.2.1.$17.0.0"></span><span class="label" data-reactid=".0.2.2.1.0.0.1.2.1.$17.0.1"><span data-reactid=".0.2.2.1.0.0.1.2.1.$17.0.1.0">36.96</span><span data-reactid=".0.2.2.1.0.0.1.2.1.$17.0.1.1">%</span></span></td><td data-reactid=".0.2.2.1.0.0.1.2.1.$17.1"><a class="" href="/ilpt-gmbh/mobile-web-client/?query=browser%3A%22Android%204.4%22" data-reactid=".0.2.2.1.0.0.1.2.1.$17.1.0">Android 4.4</a></td><td data-reactid=".0.2.2.1.0.0.1.2.1.$17.2"><time datetime="2016-01-12T15:29:09.000Z" title="January 12, 2016 3:29 PM UTC" data-reactid=".0.2.2.1.0.0.1.2.1.$17.2.0">3 days ago</time></td></tr><tr data-reactid=".0.2.2.1.0.0.1.2.1.$18"><td class="bar-cell" data-reactid=".0.2.2.1.0.0.1.2.1.$18.0"><span class="bar" style="width:13.04%;" data-reactid=".0.2.2.1.0.0.1.2.1.$18.0.0"></span><span class="label" data-reactid=".0.2.2.1.0.0.1.2.1.$18.0.1"><span data-reactid=".0.2.2.1.0.0.1.2.1.$18.0.1.0">13.04</span><span data-reactid=".0.2.2.1.0.0.1.2.1.$18.0.1.1">%</span></span></td><td data-reactid=".0.2.2.1.0.0.1.2.1.$18.1"><a class="" href="/ilpt-gmbh/mobile-web-client/?query=browser%3A%22Chrome%2011.0%22" data-reactid=".0.2.2.1.0.0.1.2.1.$18.1.0">Chrome 11.0</a></td><td data-reactid=".0.2.2.1.0.0.1.2.1.$18.2"><time datetime="2016-01-06T07:59:12.000Z" title="January 6, 2016 7:59 AM UTC" data-reactid=".0.2.2.1.0.0.1.2.1.$18.2.0">9 days ago</time></td></tr></tbody></table>

**Comment by galfert** [comment]
I'm pretty sure this will be fixed by #940.

`localStorage.length` is only called from `RemoteStorage.LocalStorage`. The PR improves the detection of localStorage availability, so the adapter wouldn't be used.

**Comment by galfert** [comment]
Closing this as #940 has been merged.
