### ISSUE TITLE
Don't throw error for failed network/sync requests

### ISSUE THREAD

**Issue by skddc** [remotestorage/remotestorage.js#923]
It's a normal situation that network requests fail, especially for an offline-first library used on mobiles. So I think we shouldn't throw actual exceptions when it happens, but rather only log a warning and maybe have an event for it that devs can use for e.g. analytics code.

**Comment by skddc** [comment]
Anyone has opinions on this?

/cc @michielbdejong @silverbucket @untitaker @galfert

**Comment by untitaker** [comment]
I don't have any opinion since the user doesn't look at console.log, though it's probably for the better when app devs are actually showing those errors to the user.

**Comment by gunar** [comment]
we should dispatch an event so the app can inform the user if it's
online/syncd or not. devs could use the same event for debugging.

**Comment by skddc** [comment]
Great, so let's turn it from an exception into an event.

Related: it'd be great to have a way to log all events from rs.js as a developer. Makes understanding the library's behaviour that much easier. @galfert and I once talked about building a browser extension, similar to Ember Inspector for that, which could also do other things, but we didn't ever do it. Maybe it's actually enough or even better to do it directly in the library, similar to [`enableLog()`](https://remotestorage.io/doc/code/files/remotestorage-js.html#RemoteStorage.enableLog) or even bound to that.

**Comment by skddc** [comment]
I just hit this exact spot with my new-widget work. The current widget goes into offline mode when a request fails and comes back online when one succeeds. `remoteStorage.remote.online` is set accordingly. But that's actually where the correct event is missing I think. Instead of a "network request failed" event, I think we need a general "went offline/online" event.

Not sure about the naming/API, though. How about this:

```js
remoteStorage.on('network-offline', () => handleOffline);
remoteStorage.on('network-online', () => handleOnline);
```

Another option:

```js
remoteStorage.on('network', (evt) => {
    switch (evt) {
        case 'offline':
            handleOffline();
            break;
        case 'online':
            handleOnline();
            break;
    }
});
```

I like number 1 better, and we do already have 'connected' and 'disconnected' for the storage itself. What do you think?

**Comment by skddc** [comment]
One thing we could add as additional event for "network" would be "synced", which we are also lacking as a specific event at the moment. Or it could be its own "sync" event with "started", "done" and so on as arguments or suffixes.

**Comment by skddc** [comment]
> Or it could be its own "sync" event with "started", "done" and so on as arguments or suffixes.

There's actually an event for this in the `Sync` class, but it's not documented and seems to be private API so far.

**Comment by skddc** [comment]
I'm done adding the events and the error is removed from the console. Not sure if I should open a seperate PR just for those commits.

**Comment by michielbdejong** [comment]
IIRC new events should be added [here](https://github.com/remotestorage/remotestorage.js/blob/master/src/remotestorage.js#L170) so they show up on https://remotestorage.github.io/remotestorage.js/files/remotestorage-js.html#RemoteStorage.Events

**Comment by skddc** [comment]
Oh right, I forgot about docs. Thanks.

**Comment by skddc** [comment]
Added the docs.
