### ISSUE TITLE
Test with Safari Technology Preview

### ISSUE THREAD

**Issue by skddc** [remotestorage/remotestorage.js#929]
Apple claims they considerably improved IndexedDB, so we can probably use it in Safari as well soon:

https://webkit.org/blog/6017/introducing-safari-technology-preview/

**Comment by gregkare** [comment]
Safari 10.0 is supposed to support 100% of the recommended IndexDB standard: https://developer.apple.com/library/prerelease/content/releasenotes/General/WhatsNewInSafari/Articles/Safari_10_0.html

**Comment by skddc** [comment]
Is that already released, or if not, when is it expected?

**Comment by galfert** [comment]
I think it's supposed to be released with the next macOS version (Sierra) in the fall.

**Comment by skddc** [comment]
LOL macOS

**Comment by skddc** [comment]
Cool. So we just need to change it sometime before fall in rs.js.

**Comment by galfert** [comment]
I'm downloading the private beta and will install it on my old Macbook to check it out.

**Comment by galfert** [comment]
I tested Webmarks with the latest Safari Technology Preview Release 8 (Safari 9.1.2) and it all worked flawlessly using IndexedDB. 🎉

**Comment by skddc** [comment]
Don't we have to remove code that makes Safari not use IndexedDB?

**Comment by galfert** [comment]
No, we only have a specific Browser/device check for Android <= 4.3. For everything else we try to create an actual database to determine if IndexedDB is supported.

**Comment by skddc** [comment]
Nice!

Did you also test how it behaves in private mode?

**Comment by galfert** [comment]
Behaves the same as the stable Safari in private mode.

**Comment by skddc** [comment]
![dislike](https://cloud.githubusercontent.com/assets/842/16729508/2fcb9596-476d-11e6-927a-2f2406980977.gif)
