### ISSUE TITLE
Problem when trying to get an unexisting remote file [cache + IndexedDB]

### ISSUE THREAD

**Issue by esroyo** [remotestorage/remotestorage.js#934]
I have a problem when trying to get an unexisting remote file where the associated promise never gets resolved. This behavior only appears  with the "cached" version, the "no-cache" works fine.
I tracked the problem down to [cachinglayer.js#L109](https://github.com/remotestorage/remotestorage.js/blob/462ecc1e01e8933244fa1b4366ee440e159b4c72/src/cachinglayer.js#L109). Looks to me like the ```isOutdated``` func always returns ```true``` for unexisting remote files (I guess there is no information in the indexeddb), so apparently this means the condition will never return 404 at that point. May be later on there is some problem with the resolution of ```queueGetRequest``` and the synchronization process for a "not found" file... I didn't look further into it, was hopping this gives you enough hints to solve it, but I can investigate further if needed. Thanks a lot.

**Comment by skddc** [comment]
Thanks for your detailed report.

Just a quick note without having looked into it yet: in my company we do use rejected promises for non-existing files in app code in production. So I assume it must be a certain case that fails, which we haven't encountered in our apps yet. Hence, and all information about surrounding code, cache status etc. would be helpful.

Just to be sure: when you say the promise doesn't get resolved, does that also mean it doesn't get rejected?

**Comment by esroyo** [comment]
Thank for your response. Finally I was able to find the bug and made a pull request #935 
Regards
