### ISSUE TITLE
Migrate to DropBox API v2

### ISSUE THREAD

**Issue by Ragnis** [remotestorage/remotestorage.js#936]
API documentation: https://www.dropbox.com/developers/documentation/http/documentation
Migration guide: https://www.dropbox.com/developers/reference/migration-guide

It seems that all the required functionality is present in the API v2.

**Comment by Ragnis** [comment]
Dropbox has now announced that API v1 will be shut down on June 28, 2017.

**Comment by skddc** [comment]
All done, thanks to @Ragnis's and @galfert's work on this. You guys rock!
