### ISSUE TITLE
Test with FF Contextual Identities in FF Nightly

### ISSUE THREAD

**Issue by skddc** [remotestorage/remotestorage.js#938]
In theory, this should enable using the same RS app with multiple accounts in the same browser window/session:

https://blog.mozilla.org/tanvi/2016/06/16/contextual-identities-on-the-web/

Can be tested with any RS-enabled app on the Web today.

**Comment by galfert** [comment]
I can confirm that this works. Used the same app with two different remoteStorage accounts.

Tested in Firefox Nightly (51.0a1) on OS X.

**Comment by skddc** [comment]
w00t!

![reggie-awesome](https://cloud.githubusercontent.com/assets/842/18386729/ab488c5e-7690-11e6-9f7b-1147217b9e9a.gif)

**Comment by skddc** [comment]
Let's put this information in the wiki before closing the issue, so it doesn't get lost/forgotten.

**Comment by skddc** [comment]
They killed this feature in FF itself and moved it to an extension: https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/
