### ISSUE TITLE
3rd party backends don't get initialized properly on first app load

### ISSUE THREAD

**Issue by galfert** [remotestorage/remotestorage.js#941]
When loading the app for the first time, the app sets the API keys only after the remoteStorage initialization has already happened. But the backends only get initialized, when there is an API key set.

So the widget shows the backend's icon, but the class hasn't been initialized, which results in an exception when clicking the icon.

When loading the app for the second time and the API key is loaded from localStorage before the backend initialization, the backend object will be created properly.

**Comment by skddc** [comment]
I don't remember any issues with those backends on first load. Do we know how/when it was introduced?

**Comment by galfert** [comment]
No, I don't know. But from looking at the code I'd say it must have been this way from the beginning.

I think I have a working fix for it. Just trying to create a test as well...

**Comment by skddc** [comment]
![bluesbrothers](https://cloud.githubusercontent.com/assets/842/16697178/bb9e48e2-4548-11e6-94fc-14409ab33d01.gif)
