### ISSUE TITLE
Check if files are marked as deleted in Dropbox's API

### ISSUE THREAD

**Issue by gregkare** [remotestorage/remotestorage.js#943]
## How to reproduce
- Go to https://mfd-dropbox.5apps.com/ (built with #928 PR)
- Connect your Dropbox account
- Add a few drinks
- Remove one of the drinks
- Try to add it again
### Expected behavior

The drink is added again and synced
### Actual behavior

The drink is added again locally but not synced because the Dropbox API responds with a JSON document saying the file exists but has been deleted (`is_deleted: true`). We then keep doing GET requests forever

It looks like we need to check the content of the JSON for the `is_deleted` attribute on files to know if they were deleted

**Comment by skddc** [comment]
It might actually make sense to migrate to API v2 first, because this is one of the things that changed:

https://www.dropbox.com/developers/reference/migration-guide#metadata-mapping

Then again, the fix is basically the same, so we can also fix the lib shooting itself in the foot before migrating, of course.

**Comment by galfert** [comment]
This seems to be fixed with #975

**Comment by skddc** [comment]
There's no new comment after you reported it's happening in that PR. Could you explain on the PR how the issue you have there is different from this one?

**Comment by galfert** [comment]
This issue is about deleting files and then not being able to create a file with the same filename again. That does work in the PR now.

The problem I still have in the PR is about receiving an error when trying to delete the very last file.

**Comment by skddc** [comment]
It's hard to piece it together from here. Please explain it over there. Thank you!

**Comment by skddc** [comment]
I just tried this with the latest `master`, containing the API v2 support. There's a 409 conflict response when recreating the document. However, it then immediately proceeds to actually create it again and that succeeds.

So it seems to me like @galfert was right. Thus I'm closing this for now. As always, feel free to re-open anytime.
