### ISSUE TITLE
Misuse of module.exports breaks remotestorage.js when a loader is used to load the script

### ISSUE THREAD

**Issue by dantman** [remotestorage/remotestorage.js#945]
[L4151-L4156](https://github.com/remotestorage/remotestorage.js/blob/master/release/stable/remotestorage.js#L4151-L4156) use `module.exports` if present to expose `RemoteStorage` instead of defining `global.RemoteStorage`.

However soon after `RemoteStorage.util` attempts to use the global `RemoteStorage` directly.

This means the script will if you try to take advantage of the export/script loading features of Webpack, Browserify, etc...

**Comment by skddc** [comment]
Thanks! Which version did you encounter the problem with?

**Comment by dantman** [comment]
The version packaged into npm as `0.12.1`.

**Comment by galfert** [comment]
I was able to reproduce the problem when trying out the current master's AMD build in [Litewrite](https://github.com/litewrite/litewrite).

I tried to figure out what changed between this version and the one that Litewrite is using at the moment. Then I noticed that Litewrite is actually using a patched version of `remoteStorage.amd.js` (e.g. with Bluebird removed). But I couldn't find the exact change that fixed this error.

@jorinvo Could you shed some light on what you did to fix this, please?

**Comment by untitaker** [comment]
I'm hitting the same problems. It seems to me that remoteStorage could use `require` everywhere and just release its builds using webpack?

**Comment by skddc** [comment]
Yes, I think ideally we switch the whole library to ES6 modules with Webpack or Browserify for packaging soon.

Also see #673, #786, #582, #501 for some related issues (that we could all solve in one go).

**Comment by skddc** [comment]
@dantman We just released a new stable version, fixing the AMD build. Also, @untitaker wrote about how he's using it with Webpack in the wiki: https://wiki.remotestorage.io/RemoteStorage.js:Beginners'_Guide#Webpack

**Comment by lesion** [comment]
I would love the whole library packed with webpack and with ES6 modules, and I could help in this task if you need !

I'm currently having issues because of this, trying to use the lib inside a chrome extension,
with chrome complaining about this `tv4` dependency (probably wrong packed 'cause I see they are using 
`this` for global context but `this` in chrome extension is not pointing to global `windows` object but to `undefined`)

**Comment by skddc** [comment]
> I would love the whole library packed with webpack and with ES6 modules, and I could help in this task if you need !

That'd be fantastic!

Due to your recent pull requests and potential future ones, I just added you to the "collaborators" group. Which means you can now create and push to branches on remoteStorage org repos. Please see https://github.com/remotestorage/remotestorage.js/blob/master/CONTRIBUTING.md for some info on branch naming and such.

> I'm currently having issues because of this, trying to use the lib inside a chrome extension,
> with chrome complaining about this tv4 dependency (probably wrong packed 'cause I see they are using
> this for global context but this in chrome extension is not pointing to global window object but to undefined)

Which build are you using and what's the exception exactly?

**Comment by lesion** [comment]
> Due to your recent pull requests and potential future ones, I just added
> you to the "collaborators" group. Which means you can now create and
> push to branches on remoteStorage org repos. Please see
> https://github.com/remotestorage/remotestorage.js/blob/master/CONTRIBUTING.md
> for some info on branch naming and such.

Wow ! I'm super happy to contribute to remoteStorage ! thanks

>     I'm currently having issues because of this, trying to use the lib
>     inside a chrome extension,
>     with chrome complaining about this tv4 dependency (probably wrong
>     packed 'cause I see they are using
>     this for global context but this in chrome extension is not pointing
>     to global window object but to undefined)
> 
> Which build are you using and what's the exception exactly?


I'm using the new 0.13.0 release from npm (amd build),
and embedding the lib with webpack inside my project.

## Exception
ReferenceError: tv4 is not defined

this is inside
[here](https://github.com/remotestorage/remotestorage.js/blob/master/src/baseclient/types.js#L134)

It's not so easy to create the setup that will reproduce this issue,
I'll create a repo to let you reproduce it in the afternoon.

thanks again

**Comment by skddc** [comment]
Ok, cool.

**Comment by lesion** [comment]
Hey, here the repo:
https://github.com/lesion/rs-issues
relative code inside `index.js`
There's also a gh-page showing the issue: https://lesion.github.io/rs-issues/

Before trying to reproduce it locally, you'll need to take care of [this issue](https://github.com/remotestorage/modules/pull/91). The PR solves it but
I've not included the builded `dist` files inside it. Should I ?

Maybe let's open a new issue for this ?
Let me know if everything is clear.

Cheers
