### ISSUE TITLE
localStorage backend (instead of IDB) used in latest Firefox

### ISSUE THREAD

**Issue by skddc** [remotestorage/remotestorage.js#950]
Don't know when this happened, but can't be long ago. In the latest Firefox desktop (tested on both Linux and OS X), rs.js uses localStorage as caching backend.

Not sure what changed in Firefox for our feature inititalization to break. But it's not necessarily a bug in our code.

**Comment by galfert** [comment]
Just tested again with latest stable FF (version 49.0.1) and it was using IndexedDB again.

**Comment by skddc** [comment]
Mine is still broken it seems. Maybe more people could test and give feedback?

**Comment by skddc** [comment]
Ok, so I tried again with a fresh profile in latest stable on both Linux and Windows, and it worked fine.

Not sure how to repair my other profile, because even after manually removing the storage files, it's still throwing an `UnknownError` when trying to open an IndexedDB. But as there's no bug with the library and nothing to fix, I'll close this issue now.

**Comment by skddc** [comment]
Just for reference: [this is a known issue in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=944918), where all IndexedDB functionality can break in this exact way. The solution is to manually delete *all* storage files.
