### ISSUE TITLE
Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.

### ISSUE THREAD

**Issue by galfert** [remotestorage/remotestorage.js#964]
When disconnecting from remoteStorage while data is synced, the following exception is thrown:

```
[Sync] Error DOMException: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
```

You can reproduce this by connecting to you account at https://webmarks.5apps.com and then immediately disconnect while it's still downloading bookmarks.

**Comment by skddc** [comment]
I think this is a duplicate of #939, no?

**Comment by galfert** [comment]
Oh, correct. I did search for the error message to find any existing issues about this, but the message was only contained in the screenshot.
