### ISSUE TITLE
"No storage information found for this user address""

### ISSUE THREAD

**Issue by lduboeuf** [remotestorage/remotestorage.js#965]
This is a follow up of 5apps help [forum post](https://5apps.tenderapp.com/discussions/problems/393-no-storage-information-found-for-this-user-address)

I face a "No storage information found for this user address" while connecting to rs.

```shell
 The page at 'https://lduboeuf.github.io/team-tool-box/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://5apps.com/.well-known/webfinger?resource=acct:lduboeuf@5apps...'. This request has been blocked; the content must be served over HTTPS.
```

**Comment by silverbucket** [comment]
Hi, by default webfinger.js will only use TLS lookups, however in remotestorage we allow non-TLS fallbacks.

Do you know if at first there's a TLS lookup at that URL that's failing before the non-TLS lookup?

**Comment by lduboeuf** [comment]
hi, unfortunately don't have more debug info.

**Comment by silverbucket** [comment]
BTW on mobile and not sure I have access to that previous 5apps discussion.

**Comment by lduboeuf** [comment]
ok, just discovered devtools option to allow debugging apps loaded in browser so here is my logs:
seems to calls https first
```
vendors.js:3 GET https://5apps.com/.well-known/webfinger?resource=acct:lduboeuf@5apps.com net::ERR_FAILEDg @ vendors.js: 3d.__fetchJRD @ vendors.js: 3e @ vendors.js:3
vendors.js:3 GET https://5apps.com/.well-known/host-meta?resource=acct:lduboeuf@5apps.com net::ERR_FAILEDg @ vendors.js:3d.__fetchJRD @ vendors.js:3e @ vendors.js:3d @ vendors.js:3f @ vendors.js:3i.onreadystatechange @ vendors.js:3
vendors.js:3 GET https://5apps.com/.well-known/host-meta.json?resource=acct:lduboeuf@5apps.com net::ERR_FAILED
```
but don't have more information cause my file is minified  ;-).

**Comment by silverbucket** [comment]
@lduboeuf thanks for that info, it helps. Looks like either the account name is incorrect or 5apps.com is failing webfinger lookups for some reason. @skddc @galfert any ideas?

**Comment by lduboeuf** [comment]
here is non-minified version debug info ;-):
```
GET https://5apps.com/.well-known/webfinger?resource=acct:lduboeuf@5apps.com net::ERR_FAILED__makeRequest 
@ remotestorage.js:5580WebFinger.__fetchJRD
 @ remotestorage.js:5583__call
 @ remotestorage.js:5723

remotestorage.js:5580 GET https://5apps.com/.well-known/host-meta?resource=acct:lduboeuf@5apps.com net::ERR_FAILED__makeRequest
 @ remotestorage.js:5580WebFinger.__fetchJRD
 @ remotestorage.js:5583__call 
@ remotestorage.js:5723__fallbackChecks
 @ remotestorage.js:5687__processState
 @ remotestorage.js:5560xhr.onreadystatechange
 @ remotestorage.js:5571

remotestorage.js:5580 GET https://5apps.com/.well-known/host-meta.json?resource=acct:lduboeuf@5apps.com net::ERR_FAILED__makeRequest
 @ remotestorage.js:5580WebFinger.__fetchJRD
 @ remotestorage.js:5583__call
 @ remotestorage.js:5723__fallbackChecks
 @ remotestorage.js:5687__processState
 @ remotestorage.js:5560xhr.onreadystatechange
 @ remotestorage.js:5571
remotestorage.js:5580 Mixed Content: The page at 'https://lduboeuf.github.io/team-tool-box/dev/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://5apps.com/.well-known/webfinger?resource=acct:lduboeuf@5apps.com'. This request has been blocked; the content must be served over HTTPS.__makeRequest ....
```

**Comment by lduboeuf** [comment]
context reminder:
happens only on mobile browser (connected through wifi), don't tried on another one yet. Tried to reset all browser datas -> nothing new. used to work before.

**Comment by skddc** [comment]
> or 5apps.com is failing webfinger lookups for some reason. @skddc @galfert any ideas?

When you request the Webfinger URLs, you can see that they work. So this is very strange.

@lduboeuf The phone and your computer (where it works) are on the same network, right?

**Comment by lduboeuf** [comment]
@skddc yes

**Comment by lduboeuf** [comment]
oops, it works again, did nothing more than trying to debug remotestorage.js in devtools
something have been done on your side ?

**Comment by lduboeuf** [comment]
well, now it is sometimes working, sometimes not... 
here i have:
https://lduboeuf.github.io/team-tool-box (use cache manifest) not working (Sync error)
https://lduboeuf.github.io/team-tool-box/dev : works
but sometimes both not works and sometimes both works...

Does rs handle well switching between url like i do ? ( i also have routes that end with '#myroute-blabla' ) and i can load my app directly with that route ( e.g: https://lduboeuf.github.io/team-tool-box/dev/#team-details )

**Comment by skddc** [comment]
That shouldn't impact any connections. It loooks like a terribly slow connection to me then. (Which can also be the phone being terribly slow.)

**Comment by lduboeuf** [comment]
very strange, my phone isn't a ferrari but my broadband and wifi is really correct. 
latency is < 100ms for 5apps

**Comment by lduboeuf** [comment]
the only thing that differ from examples i see is that i do not wait for rs to be ready 
`remoteStorage.on('ready', function() {...`
i call getAll directly [https://github.com/lduboeuf/team-tool-box/blob/master/src/app.js#L43-L59](https://github.com/lduboeuf/team-tool-box/blob/master/src/app.js#L43-L59)

**Comment by skddc** [comment]
You definitely need to wait for the `ready` event; otherwise you can't be sure that all features are loaded in time.

**Comment by lduboeuf** [comment]
ok, well that does not resolve the pb :-/ . something to do with ubuntu's browser cache system i guess.

**Comment by skddc** [comment]
I can test on an Ubuntu phone as well, but only in March. If the issue persists until then, I'll grab it from the office when I'm back in Europe and see if I can find out more.

**Comment by lduboeuf** [comment]
:+1:

**Comment by lduboeuf** [comment]
ok, i think i'm closer:
 [https://lduboeuf.github.io/team-tool-box/](https://lduboeuf.github.io/team-tool-box/) use cache manifest : stay stuck with `sync` error and [https://lduboeuf.github.io/team-tool-box/dev/](https://lduboeuf.github.io/team-tool-box/dev/), no cache manifest :  behave well.

Maybe something wrong in my [manifest](https://github.com/lduboeuf/team-tool-box/blob/gh-pages/manifest.appcache) file .
 Ubuntu touch browser implement that [recommendation](https://html.spec.whatwg.org/multipage/browsers.html#offline) for webapps offline cache handling

**Comment by skddc** [comment]
I think the NETWORK online whitelist wildcard should be just an asterisk, like so:

```
NETWORK:
*
```

You could verify this by trying to request other non-cached resources via XHR of course.

**Comment by skddc** [comment]
I just encountered this with your deployed version on GH pages. Pretty sure it's due to the AppCache rule!

**Comment by lduboeuf** [comment]
:+1:  i test with `NETWORK: *` and it seems to work! ;-) . sorry for this remotestorage unrelated issue ;-).
