### ISSUE TITLE
[Sync] Error TypeError: node.local.itemsMap is undefined

### ISSUE THREAD

**Issue by lduboeuf** [remotestorage/remotestorage.js#966]
`remotestorage 0.14`

hi,
I face this issue today. 
Any ideas ?

```
[Sync] Error TypeError: node.local.itemsMap is undefined
Trace de la pile :
RemoteStorage.Sync.prototype.autoMergeFolder@http://localhost:8000/vendors/remotestorage.js:10212:17
RemoteStorage.Sync.prototype.autoMerge@http://localhost:8000/vendors/remotestorage.js:10279:20
RemoteStorage.Sync.prototype.completeFetch/<@http://localhost:8000/vendors/remotestorage.js:10545:23
tryCatch1@http://localhost:8000/vendors/remotestorage.js:3043:18
Promise$_callHandler@http://localhost:8000/vendors/remotestorage.js:1829:13
Promise$_settlePromiseFromHandler@http://localhost:8000/vendors/remotestorage.js:1843:13
Promise$_settlePromiseAt@http://localhost:8000/vendors/remotestorage.js:2006:9
Promise$_settlePromises@http://localhost:8000/vendors/remotestorage.js:2149:9
Async$_consumeFunctionBuffer@http://localhost:8000/vendors/remotestorage.js:106:9
Async$consumeFunctionBuffer@http://localhost:8000/vendors/remotestorage.js:69:9
Promise$_Scheduler@http://localhost:8000/vendors/remotestorage.js:2766:17
```

**Comment by lduboeuf** [comment]
humm, after re login seems to be fine. Don't know what happened though.

**Comment by skddc** [comment]
Can't say I've seen this before. Thanks for putting it here anyway, so in case someone sees it again, or even better, can reproduce it, we know it's been there in `0.14`.

**Comment by lduboeuf** [comment]
really have no idea how to reproduce it, i know my network at office is sometimes bad, have high latency and http requests sometimes fail (behing a proxy). Would be nice to have a "please reconnect" in rs widget in that case.

**Comment by lduboeuf** [comment]
in one of my office PC, i kept the issue, so if  you have any things you want me to check, i can do it. or try a remote debugging (not sure if my network allow it though )

**Comment by skddc** [comment]
I'd like to help, but I'm in currently in GMT+8, which makes it a bit hard to look at it live. If it's still there next week, we could do a screensharing session. It's a bit hard to analyze the situation without one I think.

Does the problem go away when you re-connect on that PC, and then come back after a while?

**Comment by lduboeuf** [comment]
If you want to debug it i prefer not to log in again. For other devices there is no problem after re-login.

**Comment by lduboeuf** [comment]
well it will be hard to debug, without doing nothing, it works now...

**Comment by skddc** [comment]
Which app is that? If it's one of mine, I can add exception tracking via Sentry in order to log future occurrences.

**Comment by lduboeuf** [comment]
https://lduboeuf.github.io/team-tool-box 
When i reconnected with  PC 1, then synchronization worked on PC 2 (same network) without doing nothing...

**Comment by skddc** [comment]
Ideally try to capture the network requests from your browser's devtools, if/when encountering this again.
