### ISSUE TITLE
New API for loading modules

### ISSUE THREAD

**Issue by galfert** [remotestorage/remotestorage.js#968]
This is taken from https://community.remotestorage.io/t/ideas-about-api-changes-additions-in-noglobal-1-0/380.

Currently loading the modules happen implicitly by just importing them. This requires an inherent order for the imports, in that the RemoteStorage library has to be imported first.

The proposed change for the module loading could look something like

```js
import Bookmarks from 'remotestorage-module-bookmarks';
import Documents from 'remotestorage-module-documents';
import RemoteStorage from 'remotestoragejs';

let rs = new RemoteStorage({ modules: [Bookmarks, Documents] });
```

This way it would also be possible to use several remoteStorage instances that use different modules.

**Comment by galfert** [comment]
Would also be nice to be able to load additional modules at a later time.

E.g. via

```js
import Shares from 'remotestorage-module-shares';

rs.addModule(Shares);
```

**Comment by skddc** [comment]
> Would also be nice to be able to load additional modules at a later time.

Yes, good idea!

**Comment by skddc** [comment]
> This way it would also be possible to use several remoteStorage instances that use different modules.

And also use the same instance, but only attach modules when actually needed. E.g. in more complex apps, or  for browser apps on the fly. I guess, this could also have a `rs.removeModule` analog for the latter.

**Comment by lesion** [comment]
I'll do this

**Comment by lesion** [comment]
writing down required changes here:

actually a module declaration use `RemoteStorage.defineModule` and pass a `module name` and the module constructor itself; after that initialization, a module could be reached using rs.`module name` namespace. 
with proposed change the module cannot calls `defineModules` anymore, but rs itself has to initialize required modules (checking modules options or with proposed `addModule` method); we should decide where it takes `module name` than with that requirements I suppose: has to be included inside the module (so `addModule(moduleName, module)` is not an option), and the module has to export it in some way, by a property or with a method, what do you prefer? 


another question, should modules be completely independent from RemoteStorage (actually there's only the method `RemoteStorage.util.extend` as a direct dependency).

**Comment by skddc** [comment]
> with that requirements I suppose: has to be included inside the module (so addModule(moduleName, module) is not an option), and the module has to export it in some way, by a property or with a method, what do you prefer?

Could be a property like "name" or "category", yes. I think if it's defined directly in the module, that would also make it a bit more clear (as opposed to having the dev define it from the app).

> another question, should modules be completely independent from RemoteStorage (actually there's only the method RemoteStorage.util.extend as a direct dependency)?

I'm not entirely sure what you mean by that. It will have to use the BaseClient APIs in any case, no?

**Comment by lesion** [comment]
> I'm not entirely sure what you mean by that. It will have to use the BaseClient APIs in any case, no?

this is true but BaseClient constructors (privateClient and publicClient) are [passed as callback arguments](https://github.com/remotestorage/modules/blob/master/src/bookmarks.js#L12), so there's no need modules depends on remoteStorage at all (I mean, there's no need to `import` it).
correct me if I'm wrong.

**Comment by skddc** [comment]
Oh, right. No need to import it really. Any utility functions should live in their own npm modules imo (if they're very RS-specific, we could prefix the module name with `remotestorage-util-`).

**Comment by galfert** [comment]
Yes, I agree. The modules don't need to depend on or import `remoteStorage` itself.

We just need to define some interface that modules should adhere to. Like having a `category` property and some initializer/constructor method that `remoteStorage` can pass the private and public client to.

**Comment by skddc** [comment]
We actually implemented this in rs.js core and a bunch of modules a while ago. 🎉
