### ISSUE TITLE
New API for loading the widget

### ISSUE THREAD

**Issue by galfert** [remotestorage/remotestorage.js#969]
Taken from https://community.remotestorage.io/t/ideas-about-api-changes-additions-in-noglobal-1-0/380.

Similar to loading the modules, loading the widget currently requires an inherent order of first importing the remoteStorage library before the widget.

The proposed change is:

```js
import Widget from 'remotestorage-widget';
import RemoteStorage from 'remotestoragejs';

let rs = new RemoteStorage();
let widget = new Widget({remoteStorage: rs});
widget.attach('#someElement');
```

**Comment by skddc** [comment]
I think we have consensus on this one already, right? (And it's also how the widget works internally anyway, so just have to remove the addition of `displayWidget` to the `RemoteStorage` prototype.

**Comment by skddc** [comment]
As far as I can see, this is half done, but still missing the explicit `.attach()`.

**Comment by galfert** [comment]
The PR for adding the`.attach()` method is at remotestorage/remotestorage-widget#31.

**Comment by skddc** [comment]
Aaand merged. Thanks, @galfert!
