### ISSUE TITLE
Document the new library usage (import/require/global/... + new widget)

### ISSUE THREAD

**Issue by skddc** [remotestorage/remotestorage.js#972]
I think this should finally be done in the generated API docs, which are currently missing the whole intro for how to use the library.

**Comment by galfert** [comment]
Also document that users need to bring their own polyfill for promises now if they want to support older browsers.

**Comment by skddc** [comment]
I learned how Read the Docs works, and created a basic Sphinx setup with the RtD theme for our `doc` folder. I also converted the first two files to `.rst` in there, and thought about how to structure the docs. There's a special `Contributing` section now, so we can keep information for contributors seperate from library usage docs for app developers for example (and thus also create way more docs for contributing).

**Comment by skddc** [comment]
I signed up for Read the Docs and imported the branch, so it should be built automatically when pushing to that now: https://remotestoragejs.readthedocs.io/en/docs-sphinx/

The "edit on GitHub" link is wrong, because it has issues with slashes in branch names (they're converted to dashes over there).

**Comment by skddc** [comment]
Last update for today: I converted all existing files in `doc` to RST now (pandoc FTW!) and added all of them to the menu: https://remotestoragejs.readthedocs.io/en/docs-sphinx/

Automatic builds on push work like a charm, so anyone can now edit and create docs in that branch.

I think the next step would be adding a new "getting started" section and afterwards seeing how much of the existing content is still useful when editing it and what has to be deleted or rewritten entirely.
