### ISSUE TITLE
Error when trying to delete last item in directory

### ISSUE THREAD

**Issue by galfert** [remotestorage/remotestorage.js#993]
As noted in https://github.com/remotestorage/remotestorage.js/pull/975#issuecomment-301040742

> When trying to delete the last bookmark, it gets deleted locally, but I can see the item still in my Dropbox. When disconnecting and reconnecting I also see the Bookmark in Webmarks again. But then when trying to delete it again, the remove call's promise fails with an error
>
>> Cannot delete non-existing node /

This seems to happen for both the Dropbox and the Google Drive backends.

**Comment by skddc** [comment]
This even happens for the default RS backend in the master branch.

**Comment by galfert** [comment]
Oh really? I thought I had tested that and it worked for the default backend. Will remove the labels for the other backends then.
