### ISSUE TITLE
Additional sync request after disconnecting from Dropbox

### ISSUE THREAD

**Issue by galfert** [remotestorage/remotestorage.js#994]
I haven't noticed that before, but when disconnecting from Dropbox, remoteStorage still tries one last sync request afterwards that fails with a 400 (Bad Request) error. The widget then shows this:

<img width="396" alt="screen shot 2017-08-25 at 12 35 12" src="https://user-images.githubusercontent.com/843/29718710-f9e138f2-89b3-11e7-905a-0a47f55f4e4e.png">

I could not produce the same problem with neither remoteStorage nor the Google Drive backends.

**Comment by skddc** [comment]
I think you experienced #939, making this a duplicate.

**Comment by galfert** [comment]
I don't think they are duplicates. I wasn't able yet to reliably reproduce #939, but this issues happens every time on only for Dropbox.
